{{
    config(
        materialized='table',
        schema='edw_fpna',
        alias='MART_FPNA_NONAIR_PROFIT_D',
        partition_by={
            'field': 'BASIS_DATE',
            'data_type': 'date',
            'granularity': 'month'
        },
        cluster_by=['FPNA_DOMAIN_NM', 'RECENT_STATUS', 'SALE_FORM_CD']
    )
}}

/*
  [MART_FPNA_NONAIR_PROFIT_D]

  FPNA 비항공 수익/비용/지표 산출용 일 단위 MART.
  도메인 mart(숙박/렌터카/T&A/패키지/보험) + reservations + closing + mapping을 직접 받아 계산한다.
  Grain은 주문/예약 단위(1 row = 1 예약).

  ## 주요 컬럼 산출 로직

  ### 1. REVENUE (Closing 기준 Revenue, VAT 제외)
  - Closing(SALE_COMMISSION + MRT_CANCEL_COMMISSION) / 1.1을 우선 사용
  - Closing 미매칭 건: 기존 로직 폴백 (사입: GMV/1.1, 위탁: MRT_SALES_PRICE)
  - 매관 비교 시 view에서 REVENUE * 1.1로 VAT 포함 금액 산출

  ### 2. MRT_POINT_NET_AMOUNT (포인트 순액)
  - POINT_PRICE - EXCLUDED_POINT_PRICE
*/

{% set domain_configs = [
    {'cte': 'LODGEMENT', 'source_model': 'MART_FPNA_LODGMENT_PROFIT_D', 'src_alias': 'LP', 'fpna_domain_nm': 'LODGMENT', 'comment': '숙박 PROFIT MART 연결'},
    {'cte': 'RENTALCAR', 'source_model': 'MART_FPNA_RENTALCAR_PROFIT_D', 'src_alias': 'RP', 'fpna_domain_nm': 'RENTALCAR', 'comment': '렌터카 PROFIT MART 연결'},
    {'cte': 'TNA', 'source_model': 'MART_FPNA_TNA_PROFIT_D', 'src_alias': 'TP', 'fpna_domain_nm': 'TNA', 'comment': 'T&A PROFIT MART 연결'},
    {'cte': 'PACKAGE', 'source_model': 'MART_FPNA_PACKAGE_PROFIT_D', 'src_alias': 'PP', 'fpna_domain_nm': 'PACKAGE', 'comment': '패키지솔루션 PROFIT MART 연결'},
    {'cte': 'INSURANCE', 'source_model': 'MART_FPNA_INSURANCE_PROFIT_D', 'src_alias': 'IP', 'fpna_domain_nm': 'INSURANCE', 'comment': '보험 PROFIT MART 연결'}
] %}

WITH
{% for d in domain_configs %}
{{ d['cte'] }} AS (
    -- {{ d['comment'] }}
    {{ fpna_nonair_profit_domain_select(ref(d['source_model']), d['src_alias'], d['fpna_domain_nm']) }}
){% if not loop.last %},{% endif %}

{% endfor %}
, NONAIR_UNION AS (
    {% for d in domain_configs %}
    SELECT
        T.*
      , DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
    FROM {{ d['cte'] }} T
    {% if not loop.last %}UNION ALL{% endif %}
    {% endfor %}
)
, NONAIR_BASE AS (
    /*
      [CONFIRM_KST_DATE 보정]
      - 확정 전 취소(주로 WAIT_CONFIRM 단계에서 취소 완료) 케이스는 `orders.reservations.confirmed_at`이 NULL로 남아 CONFIRM_KST_DATE/CONFIRM_MONTH가 NULL인 경우가 존재한다.
      - `VIEW_FPNA_NONAIR_CGMV_REVENUE_EVENT_M(_V2)` 이벤트형 집계는 `CONFIRM_MONTH IS NOT NULL` 필터를 사용하므로, 이 케이스는 CONFIRM/CANCEL 이벤트가 모두 누락되어 FPNA Confirm CGMV가 과소 집계되고 Closing과 차이가 발생한다.
      - RECENT_STATUS='cancel' AND CONFIRM_KST_DATE IS NULL 인 건에 한해, Closing의 BASIS_DATE(=confirmation_date 기반, 대사용 기준일)로 보정한다.
      - Closing은 옵션/상품 단위이므로 (ORDER_NO, RESERVATION_NO)로 사전 집계하여 row explosion을 방지한다.
      - wait_confirm은 제외한다. (추후 확정될 수 있음)
    */
    SELECT
        S.*
      , COALESCE(R_NO.reservation_no, R_ID.reservation_no) AS RESERVATION_NO_FOR_CLOSING
    FROM NONAIR_UNION S
    LEFT JOIN {{ source('orders', 'reservations') }} R_NO
      ON S.RESVE_ID = R_NO.reservation_no
     AND R_NO.deleted_at IS NULL
    LEFT JOIN {{ source('orders', 'reservations') }} R_ID
      ON R_NO.reservation_no IS NULL
     AND S.RESVE_ID = CAST(R_ID.id AS STRING)
     AND R_ID.deleted_at IS NULL
)
, CLOSING_BASIS_DATE AS (
    SELECT
        C.ORDER_NO AS ORDER_NO
      , C.RESERVATION_NO AS RESERVATION_NO
      , MIN(C.BASIS_DATE) AS CLOSING_BASIS_DATE
    FROM {{ ref('MART_FPNA_CONFIRMATION_CLOSING_D') }} C
    GROUP BY
        C.ORDER_NO
      , C.RESERVATION_NO
)
-- 결제 건 Revenue/PG_AMOUNT를 (ORDER_NO, RESERVATION_NO) 단위로 사전 집계
, CLOSING_PAYMENT_METRICS AS (
    SELECT
        C.ORDER_NO AS ORDER_NO
      , C.RESERVATION_NO AS RESERVATION_NO
      , SUM(C.SALE_COMMISSION + C.MRT_CANCEL_COMMISSION) AS PAYMENT_REVENUE
      , SUM(C.PG_AMOUNT) AS PAYMENT_PG_AMOUNT
    FROM {{ ref('MART_FPNA_CONFIRMATION_CLOSING_D') }} C
    WHERE C.ORDER_TYPE = '결제'
    GROUP BY
        C.ORDER_NO
      , C.RESERVATION_NO
)
, REGION_TNA_MAPPING AS (
    SELECT
        CITY_NM_KEY
      , COUNTRY_NM_KEY
      , REGION_NM_KEY
      , REGION_TNA_NM
    FROM {{ ref('INT_REGION_TNA_MAPPING_KEY') }}
)
SELECT
    B.BASIS_DATE AS BASIS_DATE
  , B.CONFIRM_KST_DT AS CONFIRM_KST_DT
  , CASE
        WHEN B.RECENT_STATUS = 'cancel'
         AND B.CONFIRM_KST_DATE IS NULL
         AND C.CLOSING_BASIS_DATE IS NOT NULL
        THEN C.CLOSING_BASIS_DATE
        ELSE B.CONFIRM_KST_DATE
    END AS CONFIRM_KST_DATE
  -- 취소 접수일: 예약 시스템(reservations)에서 취소/환불 이벤트가 발생한 날짜
  -- 원천: MART_SALE_D.CANCEL_KST_DT (숙박: hotel_reservupdate_detail.reserv_date_kst, 서비스: reservation_status_logs.created_at_kst)
  , B.CANCEL_DATE AS CANCEL_DATE
  , B.CREATE_KST_DATE AS CREATE_KST_DATE
  , B.CREATE_KST_DT AS CREATE_KST_DT
  , B.TRAVEL_START_DATE AS TRAVEL_START_DATE
  , B.TRAVEL_END_DATE AS TRAVEL_END_DATE
  , B.RESVE_CANCEL_DAY_DIFF AS RESVE_CANCEL_DAY_DIFF
  , B.TRAVEL_DAYS AS TRAVEL_DAYS
  , B.PARTNER_SALES_TYPE AS PARTNER_SALES_TYPE
  , B.PARTNER_SETTLE_TYPE AS PARTNER_SETTLE_TYPE
  , B.PARTNER_ID AS PARTNER_ID
  , B.PARTNER_NM AS PARTNER_NM
  , B.PROVIDER_CD AS PROVIDER_CD
  , B.HOTEL_CAMPAIGN_ID AS HOTEL_CAMPAIGN_ID
  , B.STANDARD_CATEGORY_LV_1_CD AS STANDARD_CATEGORY_LV_1_CD
  , B.STANDARD_CATEGORY_LV_1_NM AS STANDARD_CATEGORY_LV_1_NM
  , B.STANDARD_CATEGORY_LV_2_CD AS STANDARD_CATEGORY_LV_2_CD
  , B.STANDARD_CATEGORY_LV_2_NM AS STANDARD_CATEGORY_LV_2_NM
  , B.STANDARD_CATEGORY_LV_3_CD AS STANDARD_CATEGORY_LV_3_CD
  , B.STANDARD_CATEGORY_LV_3_NM AS STANDARD_CATEGORY_LV_3_NM
  , B.BIZ_TYPE AS BIZ_TYPE
  , B.BIZ_TYPE_V2 AS BIZ_TYPE_V2
  , B.BIZ_TYPE_V3 AS BIZ_TYPE_V3
  , B.FPNA_TYPE_LV_1 AS FPNA_TYPE_LV_1
  , B.FPNA_TYPE_LV_2 AS FPNA_TYPE_LV_2
  , B.FPNA_TYPE_LV_3 AS FPNA_TYPE_LV_3
  , B.MRT_TYPE AS MRT_TYPE
  , B.CATEGORY_CD AS CATEGORY_CD
  , B.CATEGORY_NM AS CATEGORY_NM
  , B.SUB_CATEGORY_CD AS SUB_CATEGORY_CD
  , B.FPNA_CATEGORY AS FPNA_CATEGORY
  , B.TEAM_DIVISION AS TEAM_DIVISION
  , B.GID AS GID
  , B.GPID AS GPID
  , B.PRODUCT_ID AS PRODUCT_ID
  , B.PRODUCT_TITLE AS PRODUCT_TITLE
  , B.REGION_TYPE AS REGION_TYPE
  , B.REGION_NM AS REGION_NM
  , B.COUNTRY_NM AS COUNTRY_NM
  , B.CITY_NM AS CITY_NM
  , B.JEJU_FLAG AS JEJU_FLAG
  , B.DOMAIN_NM AS DOMAIN_NM
  , B.FPNA_DOMAIN_NM AS FPNA_DOMAIN_NM
  , B.SALE_FORM_CD AS SALE_FORM_CD
  , B.B2B_COUPON_FLAG AS B2B_COUPON_FLAG
  , B.B2B_POINT_FLAG AS B2B_POINT_FLAG
  , B.B2B_AGENCY_FLAG AS B2B_AGENCY_FLAG
  , B.MARKETING_PARTNER_FLAG AS MARKETING_PARTNER_FLAG
  , B.ORDER_ID AS ORDER_ID
  , B.ORDER_NO AS ORDER_NO
  , B.RESVE_ID AS RESVE_ID
  , B.RECENT_STATUS AS RECENT_STATUS
  , B.RESVE_PRSNL_CNT AS RESVE_PRSNL_CNT
  , B.CROSS_SELL_FLAG AS CROSS_SELL_FLAG
  , B.COUPON_ID AS COUPON_ID
  , B.PRODUCT_COUPON_ID AS PRODUCT_COUPON_ID
  , B.ORDER_COUPON_ID AS ORDER_COUPON_ID
  , B.COUPON_TITLE AS COUPON_TITLE
  , B.PG_NM AS PG_NM
  , B.FLIGHT_RESVE_ID AS FLIGHT_RESVE_ID
  , B.FLIGHT_CREATE_KST_DT AS FLIGHT_CREATE_KST_DT
  , B.FLIGHT_TRAVEL_START_KST_DATE AS FLIGHT_TRAVEL_START_KST_DATE
  , B.TRAVEL_ID AS TRAVEL_ID
  , B.TRAVEL_DETAIL_ID AS TRAVEL_DETAIL_ID
  , B.ACCOUNTING_PROJECT_CODE AS ACCOUNTING_PROJECT_CODE
  , B.PARTNERSHIP_CD AS PARTNERSHIP_CD
  , B.MARKETING_PARTNERSHIP_CD AS MARKETING_PARTNERSHIP_CD
  , B.PARTNERSHIP_TYPE AS PARTNERSHIP_TYPE
  , B.USER_ID AS USER_ID
  , B.MRT_STAFF_FLAG AS MRT_STAFF_FLAG
  , B.GMV AS GMV
  , B.MRT_SALES_PRICE AS MRT_SALES_PRICE
  , B.PRODUCT_COUPON_PRICE AS PRODUCT_COUPON_PRICE
  , B.ORDER_COUPON_PRICE AS ORDER_COUPON_PRICE
  , B.COUPON_PRICE AS COUPON_PRICE
  , B.POINT_PRICE AS POINT_PRICE
  , B.EXCLUDED_POINT_PRICE AS EXCLUDED_POINT_PRICE
  , B.DISCOUNT_PRICE AS DISCOUNT_PRICE
  , B.MARKETING_PARTNER_FEE AS MARKETING_PARTNER_FEE
  , B.AGENCY_FEE AS AGENCY_FEE
  , B.AFFILIATE_POINT_FEE AS AFFILIATE_POINT_FEE
  , B.CHANNEL_FEE_PRICE AS CHANNEL_FEE_PRICE
  , B.CPD_AMOUNT AS CPD_AMOUNT
  , B.CHANNEL_FEE_AMOUNT AS CHANNEL_FEE_AMOUNT
  , B.CON_MARGIN AS CON_MARGIN
  , B.COMMISSION_RATE AS COMMISSION_RATE
  , B.NET_PRICE AS NET_PRICE
  , B.DW_LOAD_DT AS DW_LOAD_DT
  , M.REGION_TNA_NM AS REGION_TNA_NM
  -- Revenue (VAT 제외): Closing 결제 Revenue 우선, 미매칭 시 기존 로직 폴백
  , COALESCE(
        CP.PAYMENT_REVENUE / 1.1
      , CASE
            WHEN B.PARTNER_SALES_TYPE = 'total' THEN B.GMV / 1.1
            ELSE B.MRT_SALES_PRICE
        END
    ) AS REVENUE
  -- 포인트 순액
  , B.POINT_PRICE - B.EXCLUDED_POINT_PRICE AS MRT_POINT_NET_AMOUNT
FROM NONAIR_BASE B
LEFT JOIN CLOSING_BASIS_DATE C
  ON B.ORDER_NO = C.ORDER_NO
 AND B.RESERVATION_NO_FOR_CLOSING = C.RESERVATION_NO
LEFT JOIN CLOSING_PAYMENT_METRICS CP
  ON B.ORDER_NO = CP.ORDER_NO
 AND B.RESERVATION_NO_FOR_CLOSING = CP.RESERVATION_NO
LEFT JOIN REGION_TNA_MAPPING M
  ON B.CITY_NM = M.CITY_NM_KEY
 AND B.COUNTRY_NM = M.COUNTRY_NM_KEY
 AND B.REGION_NM = M.REGION_NM_KEY
