{{
    config(
        materialized='table',
        schema='edw_fpna',
        alias='MART_FPNA_NONAIR_PROFIT_M',
        tags=[ 'MART', 'FPNA', 'TABLE', 'SHEET' ]
    )
}}

/* [시트 원천] NONAIR 월 집계 + 시트 전용 Closing 보강.
   결제/환불 비용 및 환불 지표(REFUND_*)를 모델에서 직접 계산한다. */

WITH
NONAIR_BASE AS (
    SELECT
        N.*
      , COALESCE(R_NO.reservation_no, R_ID.reservation_no) AS RESERVATION_NO_FOR_CLOSING
    FROM {{ ref('MART_FPNA_NONAIR_PROFIT_D') }} N
    LEFT JOIN {{ source('orders', 'reservations') }} R_NO
      ON N.RESVE_ID = R_NO.reservation_no
     AND R_NO.deleted_at IS NULL
    LEFT JOIN {{ source('orders', 'reservations') }} R_ID
      ON R_NO.reservation_no IS NULL
     AND N.RESVE_ID = CAST(R_ID.id AS STRING)
     AND R_ID.deleted_at IS NULL
    WHERE N.BASIS_DATE < CURRENT_DATE('Asia/Seoul')
      AND (DATE_TRUNC(N.CONFIRM_KST_DATE, DAY) < CURRENT_DATE('Asia/Seoul') OR N.CONFIRM_KST_DATE IS NULL)
      AND (DATE_TRUNC(N.CANCEL_DATE, DAY) < CURRENT_DATE('Asia/Seoul') OR N.CANCEL_DATE IS NULL)
      AND DATE_TRUNC(N.BASIS_DATE, MONTH) >= DATE_TRUNC(DATE_SUB(CURRENT_DATE('Asia/Seoul'), INTERVAL 3 YEAR), YEAR)
)
, CLOSING_PAYMENT_METRICS AS (
    -- FIXME(fpna): 공헌이익 대사 시작 시 결제정산 raw 기준(REVENUE/COUPON/DISCOUNT) 사용분은
    -- 모두 /1.1로 VAT 제거 후 동일 기준(VAT 제외)으로 맞춰 CON_MARGIN을 재산출해야 한다.
    -- 현재는 시트 호환을 위해 coupon/discount는 Closing 값을 그대로 사용한다.
    SELECT
        C.ORDER_NO AS ORDER_NO
      , C.RESERVATION_NO AS RESERVATION_NO
      , SUM(C.SALE_COMMISSION + C.MRT_CANCEL_COMMISSION) AS PAYMENT_REVENUE
      , SUM(C.MRT_COUPON_DISCOUNT_AMOUNT) AS PAYMENT_MRT_COUPON_AMOUNT
      , SUM(C.FREE_POINT_AMOUNT) AS PAYMENT_POINT_AMOUNT
      , SUM(CASE WHEN PD.POINT_SUM IS NOT NULL THEN COALESCE(C.FREE_POINT_AMOUNT, 0) ELSE 0 END) AS PAYMENT_EXCLUDED_POINT_AMOUNT
      , SUM(
            COALESCE(C.MRT_INSTANT_DISCOUNT_AMOUNT, 0)
          + COALESCE(C.MARGIN_DISCOUNT_AMOUNT, 0)
          + COALESCE(C.AFFILIATE_INSTANT_DISCOUNT_AMOUNT, 0)
        ) AS PAYMENT_MRT_DISCOUNT_AMOUNT
      , SUM(C.PG_AMOUNT) AS PAYMENT_PG_AMOUNT
      , SUM(C.MARKETING_PARTNERSHIP_COMMISSION) AS PAYMENT_MARKETING_PARTNER_FEE
      , SUM(C.PARTNERSHIP_COMMISSION) AS PAYMENT_AGENCY_FEE
      , SUM(
            CASE
                WHEN IFNULL(PD.IS_B2B_POINT_RSV, FALSE)
                THEN COALESCE(C.FREE_POINT_AMOUNT, 0) * 0.02
                ELSE 0
            END
        ) AS PAYMENT_AFFILIATE_POINT_FEE
    FROM {{ ref('MART_FPNA_CONFIRMATION_CLOSING_D') }} C
    LEFT JOIN {{ ref('INT_FPNA_POINT_DETAIL') }} PD
      ON C.RESERVATION_NO = PD.RESVE_ID
    WHERE C.ORDER_TYPE = '결제'
    GROUP BY
        C.ORDER_NO
      , C.RESERVATION_NO
)
, CLOSING_REFUND_DATE AS (
    SELECT
        C.ORDER_NO AS ORDER_NO
      , C.RESERVATION_NO AS RESERVATION_NO
      , MIN(C.BASIS_DATE) AS CLOSING_REFUND_DATE
    FROM {{ ref('MART_FPNA_CONFIRMATION_CLOSING_D') }} C
    WHERE C.ORDER_TYPE IN ('전체환불', '부분환불', '여행종료 후 부분환불')
    GROUP BY
        C.ORDER_NO
      , C.RESERVATION_NO
)
, CLOSING_REFUND_METRICS AS (
    -- FIXME(fpna): 공헌이익 대사 시작 시 환불정산 raw 기준(REFUND_REVENUE/REFUND_COUPON/REFUND_DISCOUNT)도
    -- /1.1로 VAT 제거 후 동일 기준(VAT 제외)으로 맞춰 REFUND_CON_MARGIN을 재산출해야 한다.
    -- 현재는 시트 호환을 위해 환불 coupon/discount는 Closing raw 값을 그대로 사용한다.
    SELECT
        C.ORDER_NO AS ORDER_NO
      , C.RESERVATION_NO AS RESERVATION_NO
      , SUM(C.MRT_COUPON_DISCOUNT_AMOUNT) AS REFUND_MRT_COUPON_AMOUNT
      , SUM(
            CASE
                WHEN PD.POINT_SUM IS NOT NULL THEN 0
                ELSE COALESCE(C.FREE_POINT_AMOUNT, 0)
            END
        ) AS REFUND_MRT_POINT_AMOUNT
      , SUM(
            COALESCE(C.MRT_INSTANT_DISCOUNT_AMOUNT, 0)
          + COALESCE(C.MARGIN_DISCOUNT_AMOUNT, 0)
          + COALESCE(C.AFFILIATE_INSTANT_DISCOUNT_AMOUNT, 0)
        ) AS REFUND_MRT_DISCOUNT_AMOUNT
      , SUM(C.PG_AMOUNT) AS REFUND_PG_AMOUNT
      , SUM(C.MARKETING_PARTNERSHIP_COMMISSION) AS REFUND_MARKETING_PARTNER_FEE
      , SUM(C.PARTNERSHIP_COMMISSION) AS REFUND_AGENCY_FEE
      , SUM(
            CASE
                WHEN IFNULL(PD.IS_B2B_POINT_RSV, FALSE)
                THEN COALESCE(C.FREE_POINT_AMOUNT, 0) * 0.02
                ELSE 0
            END
        ) AS REFUND_AFFILIATE_POINT_FEE
      , SUM(
            C.MRT_COUPON_DISCOUNT_AMOUNT
          + C.PARTNER_COUPON_DISCOUNT_AMOUNT
          + C.MRT_INSTANT_DISCOUNT_AMOUNT
          + C.MARGIN_DISCOUNT_AMOUNT
          + C.AFFILIATE_INSTANT_DISCOUNT_AMOUNT
          + C.FREE_POINT_AMOUNT
          + C.PG_AMOUNT
        ) AS REFUND_GMV
      , SUM(C.SALE_COMMISSION + C.MRT_CANCEL_COMMISSION) AS REFUND_REVENUE
    FROM {{ ref('MART_FPNA_CONFIRMATION_CLOSING_D') }} C
    LEFT JOIN {{ ref('INT_FPNA_POINT_DETAIL') }} PD
      ON C.RESERVATION_NO = PD.RESVE_ID
    WHERE C.ORDER_TYPE IN ('전체환불', '부분환불', '여행종료 후 부분환불')
    GROUP BY
        C.ORDER_NO
      , C.RESERVATION_NO
)
, ROW_ENRICHED AS (
    SELECT
        N.BASIS_DATE AS BASIS_DATE
      , N.CONFIRM_KST_DATE AS CONFIRM_KST_DATE
      , CR.CLOSING_REFUND_DATE AS REFUND_DATE
      , N.PARTNER_SETTLE_TYPE AS PARTNER_SETTLE_TYPE
      , N.ACCOUNTING_PROJECT_CODE AS ACCOUNTING_PROJECT_CODE
      , N.PARTNER_ID AS PARTNER_ID
      , N.FPNA_TYPE_LV_1 AS FPNA_TYPE_LV_1
      , N.FPNA_TYPE_LV_2 AS FPNA_TYPE_LV_2
      , N.FPNA_TYPE_LV_3 AS FPNA_TYPE_LV_3
      , N.ORDER_ID AS ORDER_ID
      , N.USER_ID AS USER_ID
      , N.GMV AS GMV
      , COALESCE(CP.PAYMENT_REVENUE / 1.1, N.REVENUE, 0) AS REVENUE
      , COALESCE(CP.PAYMENT_MRT_COUPON_AMOUNT / 1.1, N.COUPON_PRICE, 0) AS MRT_COUPON_AMOUNT
      , COALESCE(CP.PAYMENT_POINT_AMOUNT, N.POINT_PRICE, 0)
          - COALESCE(CP.PAYMENT_EXCLUDED_POINT_AMOUNT, N.EXCLUDED_POINT_PRICE, 0) AS MRT_POINT_AMOUNT
      , COALESCE(CP.PAYMENT_MRT_DISCOUNT_AMOUNT / 1.1, N.DISCOUNT_PRICE, 0) AS MRT_DISCOUNT_AMOUNT
      , COALESCE(ROUND(CP.PAYMENT_PG_AMOUNT * IFNULL(PG.PG_COM_RATE, 0.02), 2), N.CHANNEL_FEE_PRICE, 0) AS PG_FEE
      , COALESCE(CP.PAYMENT_MARKETING_PARTNER_FEE, N.MARKETING_PARTNER_FEE, 0) AS MARKETING_PARTNER_FEE
      , COALESCE(CP.PAYMENT_AGENCY_FEE, N.AGENCY_FEE, 0) AS AGENCY_FEE
      , COALESCE(CP.PAYMENT_AFFILIATE_POINT_FEE, N.AFFILIATE_POINT_FEE, 0) AS AFFILIATE_POINT_FEE
      , COALESCE(CP.PAYMENT_REVENUE / 1.1, N.REVENUE, 0)
          - (
                COALESCE(CP.PAYMENT_MRT_COUPON_AMOUNT / 1.1, N.COUPON_PRICE, 0)
              + COALESCE(CP.PAYMENT_POINT_AMOUNT, N.POINT_PRICE, 0)
              - COALESCE(CP.PAYMENT_EXCLUDED_POINT_AMOUNT, N.EXCLUDED_POINT_PRICE, 0)
              + COALESCE(CP.PAYMENT_MRT_DISCOUNT_AMOUNT / 1.1, N.DISCOUNT_PRICE, 0)
            )
          - (
                COALESCE(ROUND(CP.PAYMENT_PG_AMOUNT * IFNULL(PG.PG_COM_RATE, 0.02), 2), N.CHANNEL_FEE_PRICE, 0)
              + COALESCE(CP.PAYMENT_MARKETING_PARTNER_FEE, N.MARKETING_PARTNER_FEE, 0)
              + COALESCE(CP.PAYMENT_AGENCY_FEE, N.AGENCY_FEE, 0)
              + COALESCE(CP.PAYMENT_AFFILIATE_POINT_FEE, N.AFFILIATE_POINT_FEE, 0)
            ) AS CON_MARGIN
      , COALESCE(CRM.REFUND_MRT_COUPON_AMOUNT, 0) AS REFUND_MRT_COUPON_AMOUNT
      , COALESCE(CRM.REFUND_MRT_POINT_AMOUNT, 0) AS REFUND_MRT_POINT_AMOUNT
      , COALESCE(CRM.REFUND_MRT_DISCOUNT_AMOUNT, 0) AS REFUND_MRT_DISCOUNT_AMOUNT
      , COALESCE(ROUND(CRM.REFUND_PG_AMOUNT * IFNULL(PG.PG_COM_RATE, 0.02), 2), 0) AS REFUND_PG_FEE
      , COALESCE(CRM.REFUND_MARKETING_PARTNER_FEE, 0) AS REFUND_MARKETING_PARTNER_FEE
      , COALESCE(CRM.REFUND_AGENCY_FEE, 0) AS REFUND_AGENCY_FEE
      , COALESCE(CRM.REFUND_AFFILIATE_POINT_FEE, 0) AS REFUND_AFFILIATE_POINT_FEE
      , COALESCE(CRM.REFUND_GMV, 0) AS REFUND_GMV
      , COALESCE(CRM.REFUND_REVENUE / 1.1, 0) AS REFUND_REVENUE
      -- FIXME(fpna): 현재 REFUND_REVENUE(VAT 제외)와 refund coupon/discount(Closing raw, VAT 포함)가 혼재될 수 있다.
      -- 공헌이익 대사 착수 시 REFUND_REVENUE/REFUND_COUPON/REFUND_DISCOUNT VAT 기준을 통일해 REFUND_CON_MARGIN 재정의 필요.
      , COALESCE(CRM.REFUND_REVENUE / 1.1, 0)
          - (
                COALESCE(CRM.REFUND_MRT_COUPON_AMOUNT, 0)
              + COALESCE(CRM.REFUND_MRT_POINT_AMOUNT, 0)
              + COALESCE(CRM.REFUND_MRT_DISCOUNT_AMOUNT, 0)
            )
          - (
                COALESCE(ROUND(CRM.REFUND_PG_AMOUNT * IFNULL(PG.PG_COM_RATE, 0.02), 2), 0)
              + COALESCE(CRM.REFUND_MARKETING_PARTNER_FEE, 0)
              + COALESCE(CRM.REFUND_AGENCY_FEE, 0)
              + COALESCE(CRM.REFUND_AFFILIATE_POINT_FEE, 0)
            ) AS REFUND_CON_MARGIN
    FROM NONAIR_BASE N
    LEFT JOIN CLOSING_PAYMENT_METRICS CP
      ON N.ORDER_NO = CP.ORDER_NO
     AND N.RESERVATION_NO_FOR_CLOSING = CP.RESERVATION_NO
    LEFT JOIN CLOSING_REFUND_DATE CR
      ON N.ORDER_NO = CR.ORDER_NO
     AND N.RESERVATION_NO_FOR_CLOSING = CR.RESERVATION_NO
    LEFT JOIN CLOSING_REFUND_METRICS CRM
      ON N.ORDER_NO = CRM.ORDER_NO
     AND N.RESERVATION_NO_FOR_CLOSING = CRM.RESERVATION_NO
    LEFT JOIN {{ ref('INT_FPNA_PG_FEE') }} PG
      ON N.RESVE_ID = PG.RESVE_ID
)
SELECT
    DATE_TRUNC(BASIS_DATE, MONTH) AS BASIS_MONTH
  , DATE_TRUNC(CONFIRM_KST_DATE, MONTH) AS CONFIRM_MONTH
  , DATE_TRUNC(REFUND_DATE, MONTH) AS REFUND_MONTH
  , PARTNER_SETTLE_TYPE
  , ACCOUNTING_PROJECT_CODE
  , PARTNER_ID
  , FPNA_TYPE_LV_1
  , FPNA_TYPE_LV_2
  , FPNA_TYPE_LV_3
  , SUM(GMV) AS GMV
  -- FIXME(fpna): 매관 기준 대사 호환을 위해 REVENUE/COUPON/DISCOUNT는 최종 노출 시 VAT 포함(*1.1)으로 제공함.
  -- 내부 CON_MARGIN 계산은 VAT 제외 기준이므로, 대사 기준 확정 시 노출 기준 재정의 필요.
  , SUM(REVENUE) * 1.1 AS REVENUE
  , SUM(MRT_COUPON_AMOUNT) * 1.1 AS MRT_COUPON_AMOUNT
  , SUM(MRT_POINT_AMOUNT) AS MRT_POINT_AMOUNT
  , SUM(MRT_DISCOUNT_AMOUNT) * 1.1 AS MRT_DISCOUNT_AMOUNT
  , SUM(PG_FEE) AS PG_FEE
  , SUM(MARKETING_PARTNER_FEE) AS MARKETING_PARTNER_FEE
  , SUM(AGENCY_FEE) AS AGENCY_FEE
  , SUM(AFFILIATE_POINT_FEE) AS AFFILIATE_POINT_FEE
  , SUM(CON_MARGIN) AS CON_MARGIN
  , COUNT(DISTINCT ORDER_ID) AS ORDER_CNT
  , COUNT(DISTINCT CASE WHEN CONFIRM_KST_DATE IS NOT NULL THEN ORDER_ID END) AS C_ORDER_CNT
  , COUNT(DISTINCT USER_ID) AS USER_CNT
  , COUNT(DISTINCT CASE WHEN CONFIRM_KST_DATE IS NOT NULL THEN USER_ID END) AS C_USER_CNT
  , SUM(REFUND_MRT_COUPON_AMOUNT) AS REFUND_MRT_COUPON_AMOUNT
  , SUM(REFUND_MRT_POINT_AMOUNT) AS REFUND_MRT_POINT_AMOUNT
  , SUM(REFUND_MRT_DISCOUNT_AMOUNT) AS REFUND_MRT_DISCOUNT_AMOUNT
  , SUM(REFUND_PG_FEE) AS REFUND_PG_FEE
  , SUM(REFUND_MARKETING_PARTNER_FEE) AS REFUND_MARKETING_PARTNER_FEE
  , SUM(REFUND_AGENCY_FEE) AS REFUND_AGENCY_FEE
  , SUM(REFUND_AFFILIATE_POINT_FEE) AS REFUND_AFFILIATE_POINT_FEE
  , SUM(REFUND_GMV) AS REFUND_GMV
  , SUM(REFUND_REVENUE) * 1.1 AS REFUND_REVENUE
  , SUM(REFUND_CON_MARGIN) AS REFUND_CON_MARGIN
FROM ROW_ENRICHED
GROUP BY
    DATE_TRUNC(BASIS_DATE, MONTH)
  , DATE_TRUNC(CONFIRM_KST_DATE, MONTH)
  , DATE_TRUNC(REFUND_DATE, MONTH)
  , PARTNER_SETTLE_TYPE
  , ACCOUNTING_PROJECT_CODE
  , PARTNER_ID
  , FPNA_TYPE_LV_1
  , FPNA_TYPE_LV_2
  , FPNA_TYPE_LV_3
