{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'insert_overwrite',
        schema='edw_mart',
        alias='MART_SKU_STOCK_HISTORY_D',
        partition_by={
            'field': 'SNP_DATE',
            'data_type': 'date',
            'granularity': 'day',
            'copy_partitions': true
        },
        enabled=false
    )
}}

WITH FPNA_COMMERCE_PURCHASE_TOTAL AS (
SELECT T.BASIS_DATE
    ,  T.SKU_ID
    ,  T.TICKET_AMOUNT
    ,  T.STOCK_UNIT_PRICE
    ,  T.TOTAL_TICKET_AMOUNT
    ,  LAG(T.TOTAL_TICKET_AMOUNT) OVER (PARTITION BY T.SKU_ID ORDER BY TOTAL_TICKET_AMOUNT) AS PREV_TOTAL_TICKET_AMOUNT
  FROM (
    SELECT t.BASIS_DATE
        ,  t.SKU_ID
        ,  t.TICKET_AMOUNT
        ,  t.STOCK_UNIT_PRICE
        ,  SUM(t.TICKET_AMOUNT) OVER (
            PARTITION BY t.SKU_ID
            ORDER BY t.BASIS_DATE
            ROWS UNBOUNDED PRECEDING
        ) AS TOTAL_TICKET_AMOUNT
      FROM {{ ref('SKU_PURCHASE_PRICE') }} t
    ) T
),
FPNA_COMMERCE_PURCHASE_TOTAL_AFT AS (
SELECT T.BASIS_DATE
    ,  T.SKU_ID
    ,  T.TICKET_AMOUNT
    ,  CASE WHEN T.TOTAL_TICKET_AMOUNT <= S.SALE_AMOUNT THEN T.TOTAL_TICKET_AMOUNT - S.SALE_AMOUNT
            WHEN S.SALE_AMOUNT BETWEEN IFNULL(T.PREV_TOTAL_TICKET_AMOUNT, 0) AND T.TOTAL_TICKET_AMOUNT THEN T.TOTAL_TICKET_AMOUNT - S.SALE_AMOUNT
            ELSE T.TICKET_AMOUNT END AS TICKET_AMOUNT_AFT
    ,  T.STOCK_UNIT_PRICE
    ,  T.TOTAL_TICKET_AMOUNT
    ,  T.PREV_TOTAL_TICKET_AMOUNT
    ,  S.SALE_AMOUNT
    ,  ROW_NUMBER() OVER (PARTITION BY T.SKU_ID ORDER BY T.BASIS_DATE) AS RN
FROM FPNA_COMMERCE_PURCHASE_TOTAL T
LEFT JOIN {{ ref('SALES_SKU_PURCHASE') }} S ON T.SKU_ID = S.SKU_ID AND S.SALES_TYPE = 'SALES'
),

-- AMOUNT = 0이고, 최근 입고된 물량이 아닌 로우 삭제(해당 물량이 마지막 물량일 경우, 매입가 히스토리 관리를 위해)
FPNA_COMMERCE_PURCHASE_SKU_ZERO AS (
  SELECT T.SKU_ID
    FROM (
      SELECT P.SKU_ID
          ,  COUNT(1) AS CNT_ROW
          ,  COUNT(CASE WHEN P.TICKET_AMOUNT_AFT <= 0 THEN 1 ELSE NULL END) AS CNT_ZERO
        FROM FPNA_COMMERCE_PURCHASE_TOTAL_AFT P
      GROUP BY P.SKU_ID
  ) T
  WHERE CNT_ROW = CNT_ZERO
),
FPNA_COMMERCE_PURCHASE_MAX_RN AS (
  SELECT P.SKU_ID AS SKU_ID
         ,  MAX(P.RN) AS RN
    FROM FPNA_COMMERCE_PURCHASE_TOTAL_AFT P
   WHERE P.TICKET_AMOUNT_AFT <= 0
   GROUP BY P.SKU_ID
),
FPNA_COMMERCE_PURCHASE_TOTAL_CLEAN AS (
SELECT P.BASIS_DATE AS BASIS_DATE
    ,  P.SKU_ID AS SKU_ID
    ,  P.TICKET_AMOUNT AS TICKET_AMOUNT
    ,  P.TICKET_AMOUNT_AFT AS TICKET_AMOUNT_AFT
    ,  P.STOCK_UNIT_PRICE AS STOCK_UNIT_PRICE
  FROM FPNA_COMMERCE_PURCHASE_TOTAL_AFT P
  LEFT JOIN FPNA_COMMERCE_PURCHASE_MAX_RN M1 ON P.SKU_ID = M1.SKU_ID AND P.RN < M1.RN
  LEFT JOIN FPNA_COMMERCE_PURCHASE_MAX_RN M2 ON P.SKU_ID = M2.SKU_ID AND P.RN <= M2.RN
  LEFT JOIN FPNA_COMMERCE_PURCHASE_SKU_ZERO S ON P.SKU_ID = S.SKU_ID
  WHERE CASE WHEN S.SKU_ID IS NULL THEN M2.SKU_ID IS NULL ELSE M1.SKU_ID IS NULL END
),

-- 전날 Sales 마트 취소분 반영(로우가 남아있는 가장 오래된 값에 재고 합산)
FPNA_COMMERCE_PURCHASE_TOTAL_CLEAN_C AS (
SELECT P.BASIS_DATE AS BASIS_DATE
    ,  P.SKU_ID AS SKU_ID
    ,  P.TICKET_AMOUNT AS TICKET_AMOUNT
    ,  P.TICKET_AMOUNT_AFT AS TICKET_AMOUNT_AFT
    ,  CASE WHEN P.RN = 1 THEN P.TICKET_AMOUNT_AFT + IFNULL(C.SALE_AMOUNT, 0)
            ELSE P.TICKET_AMOUNT_AFT END AS TICKET_AMOUNT_AFT_C
    ,  P.STOCK_UNIT_PRICE AS STOCK_UNIT_PRICE
    ,  P.RN
  FROM (
    SELECT P.BASIS_DATE
    ,  P.SKU_ID
    ,  P.TICKET_AMOUNT
    ,  P.TICKET_AMOUNT_AFT
    ,  P.STOCK_UNIT_PRICE
    ,  ROW_NUMBER() OVER (PARTITION BY P.SKU_ID ORDER BY P.BASIS_DATE) AS RN
    FROM FPNA_COMMERCE_PURCHASE_TOTAL_CLEAN P
  ) P
  LEFT JOIN {{ ref('SALES_SKU_PURCHASE') }} C ON C.SKU_ID = P.SKU_ID AND C.SALES_TYPE = 'CANCEL'
)
SELECT P.BASIS_DATE AS BASIS_DATE
     ,  P.SKU_ID AS SKU_ID
     ,  P.TICKET_AMOUNT_AFT_C AS TICKET_AMOUNT
     ,  P.STOCK_UNIT_PRICE AS STOCK_UNIT_PRICE
FROM FPNA_COMMERCE_PURCHASE_TOTAL_CLEAN_C P