repos:
  - repo: https://github.com/ambv/black
    rev: '24.10.0'
    hooks:
      - id: black
        language_version: python
        args:
          - "--config"
          - ".pyproject.toml"

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]
