{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'insert_overwrite',
        schema='edw_mart',
        alias='SNP_STOCK_D',
        partition_by={
            'field': 'BASIS_DATE',
            'data_type': 'date',
            'granularity': 'day',
            'copy_partitions': true
        }
    )
}}


WITH STOCK_TODAY_FLAG AS (
    SELECT T.RECORD_ID AS RECORD_ID
         ,  MAX(CASE WHEN T.TODAY_UPLOAD_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_UPLOAD_FLAG
         ,  MAX(CASE WHEN T.TODAY_SOLD_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_SOLD_FLAG
         ,  MAX(CASE WHEN T.TODAY_RESTORE_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_RESTORE_FLAG
         ,  MAX(CASE WHEN T.TODAY_END_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_END_FLAG
         ,  MAX(CASE WHEN T.TODAY_DELETE_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_DELETE_FLAG
         ,  MAX(CASE WHEN T.TODAY_CANCEL_FLAG = 1 THEN 1 ELSE 0 END) AS TODAY_CANCEL_FLAG
    FROM (
             SELECT H.file_record_id AS RECORD_ID
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'upload' THEN 1 ELSE 0 END AS TODAY_UPLOAD_FLAG
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'sold' THEN 1 ELSE 0 END AS TODAY_SOLD_FLAG
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'restore' THEN 1 ELSE 0 END AS TODAY_RESTORE_FLAG
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'end' THEN 1 ELSE 0 END AS TODAY_END_FLAG
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'delete' THEN 1 ELSE 0 END AS TODAY_DELETE_FLAG
                  ,  CASE WHEN JSON_EXTRACT_SCALAR(H.after, '$.status') = 'cancel' THEN 1 ELSE 0 END AS TODAY_CANCEL_FLAG
             FROM {{ source('mrt_20_stream', 'bulk_invoice_file_record_histories') }} H
             WHERE CAST(TIMESTAMP_ADD(H.created_at, INTERVAL 9 HOUR) AS DATE) = '{{ var("logical_start_date_kst") }}'
         ) T
    GROUP BY T.RECORD_ID
)
SELECT  d.BASIS_DATE AS BASIS_DATE
     ,  d.PRODUCT_ID AS PRODUCT_ID
     ,  d.OPTION_ID AS OPTION_ID
     ,  d.OPTION_NM AS OPTION_NM
     ,  d.VOUCHER_TYPE AS VOUCHER_TYPE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'upload' THEN 1 ELSE NULL END), 0) AS UPLOAD_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'upload' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS UPLOAD_STATUS_STOCK_PRICE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'sold' THEN 1 ELSE NULL END), 0) AS SOLD_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'sold' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS SOLD_STATUS_STOCK_PRICE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'restore' THEN 1 ELSE NULL END), 0) AS RESTORE_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'restore' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS RESTORE_STATUS_STOCK_PRICE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'end' THEN 1 ELSE NULL END), 0) AS END_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'end' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS END_STATUS_STOCK_PRICE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'delete' THEN 1 ELSE NULL END), 0) AS DELETE_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'delete' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS DELETE_STATUS_STOCK_PRICE
     ,  IFNULL(COUNT(CASE WHEN d.RECORD_RECENT_STATUS = 'cancel' THEN 1 ELSE NULL END), 0) AS CANCEL_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN d.RECORD_RECENT_STATUS = 'cancel' THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS CANCEL_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(sf.TODAY_UPLOAD_FLAG), 0) AS TODAY_UPLOAD_STATUS_CNT
     ,  IFNULL(SUM(sf.TODAY_SOLD_FLAG), 0) AS TODAY_SOLD_STATUS_CNT
     ,  IFNULL(SUM(sf.TODAY_RESTORE_FLAG), 0) AS TODAY_RESTORE_STATUS_CNT
     ,  IFNULL(SUM(sf.TODAY_END_FLAG), 0) AS TODAY_END_STATUS_CNT
     ,  IFNULL(SUM(sf.TODAY_DELETE_FLAG), 0) AS TODAY_DELETE_STATUS_CNT
     ,  IFNULL(SUM(sf.TODAY_CANCEL_FLAG), 0) AS TODAY_CANCEL_STATUS_CNT
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_UPLOAD_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_UPLOAD_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_SOLD_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_SOLD_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_RESTORE_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_RESTORE_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_END_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_END_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_DELETE_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_DELETE_STATUS_STOCK_PRICE
     ,  IFNULL(SUM(CASE WHEN sf.TODAY_CANCEL_FLAG = 1 THEN d.STOCK_UNIT_PRICE ELSE 0 END), 0) AS TODAY_CANCEL_STATUS_STOCK_PRICE
     ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM {{ ref('MART_STOCK_ROW_SNP') }} d
LEFT JOIN STOCK_TODAY_FLAG sf ON d.RECORD_ID = sf.RECORD_ID
WHERE d.BASIS_DATE = '{{ var("logical_start_date_kst") }}'
GROUP BY d.BASIS_DATE, d.PRODUCT_ID, d.OPTION_ID, d.OPTION_NM, d.VOUCHER_TYPE