{% macro fpna_nonair_profit_domain_select(src_relation, src_alias, fpna_domain_nm) -%}
-- FPNA NONAIR PROFIT 표준 스키마 생성 (도메인별 UNION 정합성 유지용)
SELECT
    {{ src_alias }}.BASIS_DATE AS BASIS_DATE,
    {{ src_alias }}.CONFIRM_KST_DT AS CONFIRM_KST_DT,
    {{ src_alias }}.CONFIRM_KST_DATE AS CONFIRM_KST_DATE,
    {{ src_alias }}.CANCEL_DATE AS CANCEL_DATE,
    {{ src_alias }}.CREATE_KST_DATE AS CREATE_KST_DATE,
    {{ src_alias }}.CREATE_KST_DT AS CREATE_KST_DT,
    {{ src_alias }}.TRAVEL_START_DATE AS TRAVEL_START_DATE,
    {{ src_alias }}.TRAVEL_END_DATE AS TRAVEL_END_DATE,
    {{ src_alias }}.RESVE_CANCEL_DAY_DIFF AS RESVE_CANCEL_DAY_DIFF,
    {{ src_alias }}.TRAVEL_DAYS AS TRAVEL_DAYS,
    {{ src_alias }}.PARTNER_SALES_TYPE AS PARTNER_SALES_TYPE,
    {{ src_alias }}.PARTNER_SETTLE_TYPE AS PARTNER_SETTLE_TYPE,
    {{ src_alias }}.PARTNER_ID AS PARTNER_ID,
    {{ src_alias }}.PARTNER_NM AS PARTNER_NM,
    {{ src_alias }}.PROVIDER_CD AS PROVIDER_CD,
    {{ src_alias }}.HOTEL_CAMPAIGN_ID AS HOTEL_CAMPAIGN_ID,
    {{ src_alias }}.STANDARD_CATEGORY_LV_1_CD AS STANDARD_CATEGORY_LV_1_CD,
    {{ src_alias }}.STANDARD_CATEGORY_LV_1_NM AS STANDARD_CATEGORY_LV_1_NM,
    {{ src_alias }}.STANDARD_CATEGORY_LV_2_CD AS STANDARD_CATEGORY_LV_2_CD,
    {{ src_alias }}.STANDARD_CATEGORY_LV_2_NM AS STANDARD_CATEGORY_LV_2_NM,
    {{ src_alias }}.STANDARD_CATEGORY_LV_3_CD AS STANDARD_CATEGORY_LV_3_CD,
    {{ src_alias }}.STANDARD_CATEGORY_LV_3_NM AS STANDARD_CATEGORY_LV_3_NM,
    {{ src_alias }}.BIZ_TYPE AS BIZ_TYPE,
    {{ src_alias }}.BIZ_TYPE_V2 AS BIZ_TYPE_V2,
    {{ src_alias }}.BIZ_TYPE_V3 AS BIZ_TYPE_V3,
    TYPE_V3.FPNA_TYPE_LV_1 AS FPNA_TYPE_LV_1,
    TYPE_V3.FPNA_TYPE_LV_2 AS FPNA_TYPE_LV_2,
    TYPE_V3.FPNA_TYPE_LV_3 AS FPNA_TYPE_LV_3,
    {{ src_alias }}.MRT_TYPE AS MRT_TYPE,
    {{ src_alias }}.CATEGORY_CD AS CATEGORY_CD,
    {{ src_alias }}.CATEGORY_NM AS CATEGORY_NM,
    {{ src_alias }}.SUB_CATEGORY_CD AS SUB_CATEGORY_CD,
    {{ src_alias }}.FPNA_CATEGORY AS FPNA_CATEGORY,
    {{ src_alias }}.TEAM_DIVISION AS TEAM_DIVISION,
    {{ src_alias }}.GID AS GID,
    {{ src_alias }}.GPID AS GPID,
    {{ src_alias }}.PRODUCT_ID AS PRODUCT_ID,
    {{ src_alias }}.PRODUCT_TITLE AS PRODUCT_TITLE,
    {{ src_alias }}.REGION_TYPE AS REGION_TYPE,
    {{ src_alias }}.REGION_NM AS REGION_NM,
    {{ src_alias }}.COUNTRY_NM AS COUNTRY_NM,
    {{ src_alias }}.CITY_NM AS CITY_NM,
    {{ src_alias }}.JEJU_FLAG AS JEJU_FLAG,
    {{ src_alias }}.DOMAIN_NM AS DOMAIN_NM,
    '{{ fpna_domain_nm }}' AS FPNA_DOMAIN_NM,
    {{ src_alias }}.SALE_FORM_CD AS SALE_FORM_CD,
    CASE WHEN {{ src_alias }}.BIZ_TYPE_V2 like 'B2B_AFFILIATE_COUPON%' THEN 'Y' ELSE 'N' END AS B2B_COUPON_FLAG,
    CASE WHEN {{ src_alias }}.BIZ_TYPE_V2 like 'B2B_AFFILIATE_POINT%' THEN 'Y' ELSE 'N' END AS B2B_POINT_FLAG,
    CASE WHEN {{ src_alias }}.BIZ_TYPE_V2 like 'B2B_AGENCY%' THEN 'Y' ELSE 'N' END AS B2B_AGENCY_FLAG,
    CASE WHEN {{ src_alias }}.MARKETING_PARTNERSHIP_CD is not null THEN 'Y' ELSE 'N' END AS MARKETING_PARTNER_FLAG,
    {{ src_alias }}.ORDER_ID AS ORDER_ID,
    {{ src_alias }}.ORDER_NO AS ORDER_NO,
    {{ src_alias }}.RESVE_ID AS RESVE_ID,
    {{ src_alias }}.RECENT_STATUS AS RECENT_STATUS,
    {{ src_alias }}.RESVE_PRSNL_CNT AS RESVE_PRSNL_CNT,
    {{ src_alias }}.CROSS_SELL_FLAG AS CROSS_SELL_FLAG,
    {{ src_alias }}.COUPON_ID AS COUPON_ID,
    {{ src_alias }}.PRODUCT_COUPON_ID AS PRODUCT_COUPON_ID,
    {{ src_alias }}.ORDER_COUPON_ID AS ORDER_COUPON_ID,
    {{ src_alias }}.COUPON_TITLE AS COUPON_TITLE,
    {{ src_alias }}.PG_NM AS PG_NM,
    {{ src_alias }}.FLIGHT_RESVE_ID AS FLIGHT_RESVE_ID,
    {{ src_alias }}.FLIGHT_CREATE_KST_DT AS FLIGHT_CREATE_KST_DT,
    {{ src_alias }}.FLIGHT_TRAVEL_START_KST_DATE AS FLIGHT_TRAVEL_START_KST_DATE,
    {{ src_alias }}.TRAVEL_ID AS TRAVEL_ID,
    {{ src_alias }}.TRAVEL_DETAIL_ID AS TRAVEL_DETAIL_ID,
    {{ src_alias }}.ACCOUNTING_PROJECT_CODE AS ACCOUNTING_PROJECT_CODE,
    {{ src_alias }}.PARTNERSHIP_CD AS PARTNERSHIP_CD,
    {{ src_alias }}.MARKETING_PARTNERSHIP_CD AS MARKETING_PARTNERSHIP_CD,
    {{ src_alias }}.PARTNERSHIP_TYPE AS PARTNERSHIP_TYPE,
    {{ src_alias }}.USER_ID AS USER_ID,
    {{ src_alias }}.MRT_STAFF_FLAG AS MRT_STAFF_FLAG,
    {{ src_alias }}.SALES_KRW_PRICE AS GMV,
    {{ src_alias }}.MRT_SALES_PRICE AS MRT_SALES_PRICE,
    {{ src_alias }}.PRODUCT_COUPON_PRICE AS PRODUCT_COUPON_PRICE,
    {{ src_alias }}.ORDER_COUPON_PRICE AS ORDER_COUPON_PRICE,
    {{ src_alias }}.COUPON_PRICE AS COUPON_PRICE,
    {{ src_alias }}.POINT_PRICE AS POINT_PRICE,
    {{ src_alias }}.EXCLUDED_POINT_PRICE AS EXCLUDED_POINT_PRICE,
    {{ src_alias }}.DISCOUNT_PRICE AS DISCOUNT_PRICE,
    {{ src_alias }}.MARKETING_PARTNER_FEE AS MARKETING_PARTNER_FEE,
    {{ src_alias }}.AGENCY_FEE AS AGENCY_FEE,
    {{ src_alias }}.AFFILIATE_POINT_FEE AS AFFILIATE_POINT_FEE,
    {{ src_alias }}.CHANNEL_FEE_PRICE AS CHANNEL_FEE_PRICE,
    ifnull({{ src_alias }}.COUPON_PRICE,0) + ifnull({{ src_alias }}.POINT_PRICE,0) - ifnull({{ src_alias }}.EXCLUDED_POINT_PRICE,0) + ifnull({{ src_alias }}.DISCOUNT_PRICE,0) AS CPD_AMOUNT,
    ifnull({{ src_alias }}.MARKETING_PARTNER_FEE,0) + ifnull({{ src_alias }}.AGENCY_FEE,0) + ifnull({{ src_alias }}.AFFILIATE_POINT_FEE,0) + ifnull({{ src_alias }}.CHANNEL_FEE_PRICE,0) AS CHANNEL_FEE_AMOUNT,
    ifnull({{ src_alias }}.MRT_SALES_PRICE,0)
      - (ifnull({{ src_alias }}.COUPON_PRICE,0) + ifnull({{ src_alias }}.POINT_PRICE,0) - ifnull({{ src_alias }}.EXCLUDED_POINT_PRICE,0) + ifnull({{ src_alias }}.DISCOUNT_PRICE,0))
      - (ifnull({{ src_alias }}.MARKETING_PARTNER_FEE,0) + ifnull({{ src_alias }}.AGENCY_FEE,0) + ifnull({{ src_alias }}.AFFILIATE_POINT_FEE,0) + ifnull({{ src_alias }}.CHANNEL_FEE_PRICE,0)) AS CON_MARGIN,
    {{ src_alias }}.COMMISSION_RATE AS COMMISSION_RATE,
    {{ src_alias }}.NET_PRICE AS NET_PRICE
FROM {{ src_relation }} {{ src_alias }}
LEFT JOIN {{ ref('FPNA_TYPE_V3') }} AS TYPE_V3 on TYPE_V3.BIZ_TYPE_V3 = {{ src_alias }}.BIZ_TYPE_V3
{%- endmacro %}
