{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='DIM_CROSS_SELL'
    )
}}

WITH TARGET_RESERV AS (
    SELECT A.RESVE_ID
        ,  IF(COUNT(1) > 1, 'Y', 'N') AS CANCEL_FLAG
      FROM {{ ref('INT_SALE_BASE_D') }} A
    WHERE A.CONFIRM_KST_DT IS NOT NULL
    GROUP BY A.RESVE_ID
),
-- 항공이용 목적
PNR_INFORMATION AS (
SELECT CONCAT('f', A.PNR_NO) AS RESVE_ID
    ,  SUM(IF(A.PAX_GEN = '1', 1, 0)) AS MALE_SUM
    ,  SUM(IF(A.PAX_GEN = '2', 1, 0)) AS FEMALE_SUM
    ,  MAX(A.PAX_AGE) AS MAX_PAX_AGE
    ,  MIN(A.PAX_AGE) AS MIN_PAX_AGE
    ,  MAX(RESVE_PRSNL_CNT) AS RESVE_PRSNL_CNT
  FROM TARGET_RESERV T
  LEFT JOIN {{ ref('MART_AIR_SALE_D') }} A ON T.RESVE_ID = CONCAT('f', A.PNR_NO)
  WHERE A.KIND = 1
GROUP BY A.PNR_NO
),
FLIGHT_PURPOSE AS (
SELECT A.RESVE_ID
    ,  CASE WHEN A.RESVE_PRSNL_CNT = 1 THEN 'alone'
            WHEN A.RESVE_PRSNL_CNT = 2 AND A.MALE_SUM = 1 AND A.FEMALE_SUM = 1 THEN 'lover'
            WHEN A.RESVE_PRSNL_CNT >= 2 THEN CASE WHEN A.MIN_PAX_AGE < 20 AND (A.MAX_PAX_AGE - A.MIN_PAX_AGE) > 20 THEN 'children'
                                                  WHEN A.MAX_PAX_AGE > 50 AND (A.MAX_PAX_AGE - A.MIN_PAX_AGE) > 20 THEN 'parents'
                                                  WHEN A.MALE_SUM = A.RESVE_PRSNL_CNT OR A.FEMALE_SUM = A.RESVE_PRSNL_CNT THEN 'friends'
                                                  ELSE 'friends' END
            ELSE 'friends' END AS FLIGHT_PURPOSE_TYPE
  FROM PNR_INFORMATION A
),
-- 항공 크로스셀 관련 계산
RESERV_DATE_DIFF AS (
SELECT A.RESVE_ID
    ,  A.USER_ID
    ,  T.CANCEL_FLAG
    ,  A.CREATE_KST_DT
    ,  A.TRAVEL_START_KST_DATE
    ,  A.TRAVEL_END_KST_DATE
    ,  DATE_DIFF(A.TRAVEL_START_KST_DATE, LAG(A.TRAVEL_START_KST_DATE) OVER (PARTITION BY A.USER_ID ORDER BY A.TRAVEL_START_KST_DATE), DAY) AS DATE_DIFF
  FROM TARGET_RESERV T
  LEFT JOIN {{ ref('INT_SALE_BASE_D') }} A ON T.RESVE_ID = A.RESVE_ID
  WHERE A.KIND = 1
),
RESERV_TRAVEL_ORDER AS (
SELECT T.RESVE_ID
    ,  T.USER_ID
    ,  T.CANCEL_FLAG
    ,  T.CREATE_KST_DT
    ,  T.TRAVEL_START_KST_DATE
    ,  T.TRAVEL_END_KST_DATE
    ,  T.DATE_DIFF
    ,  SUM(T.NEW_TRAVEL_FLAG) OVER (PARTITION BY T.USER_ID ORDER BY T.TRAVEL_START_KST_DATE) AS TRAVEL_ORDER
  FROM (
SELECT A.RESVE_ID
    ,  A.USER_ID
    ,  A.CANCEL_FLAG
    ,  A.CREATE_KST_DT
    ,  A.TRAVEL_START_KST_DATE
    ,  A.TRAVEL_END_KST_DATE
    ,  A.DATE_DIFF
    ,  CASE WHEN DATE_DIFF IS NULL THEN 1
            WHEN DATE_DIFF <= 15 THEN 0
            ELSE 1 END AS NEW_TRAVEL_FLAG
  FROM RESERV_DATE_DIFF A
  ) T
),
CREATE_TRAVEL_ID AS (
SELECT O.RESVE_ID
    ,  O.USER_ID
    ,  O.CANCEL_FLAG
    ,  O.CREATE_KST_DT
    ,  O.TRAVEL_START_KST_DATE
    ,  O.TRAVEL_END_KST_DATE
    ,  CONCAT(O.USER_ID, '-', O.TRAVEL_ORDER) AS TRAVEL_ID
    ,  ROW_NUMBER() OVER(PARTITION BY CONCAT(O.USER_ID, '-', O.TRAVEL_ORDER) ORDER BY O.TRAVEL_START_KST_DATE) AS TRAVEL_DETAIL_ID
  FROM RESERV_TRAVEL_ORDER O
),
FLIGHT_RESVE_INFORMATION AS (
SELECT M.TRAVEL_ID
    ,  M.FLIGHT_RESVE_ID
    ,  C.CANCEL_FLAG AS CANCEL_FLAG
    ,  CASE WHEN P.TRIP_TYPE_CD <> 'OW'
             AND P.DEPART_KST_DT <> P.RETURN_KST_DT THEN 'Y' ELSE 'N' END AS CLOSS_SELL_CONDITION_FLAG
    ,  C.CREATE_KST_DT AS FLIGHT_CREATE_KST_DT
    ,  C.TRAVEL_START_KST_DATE AS FLIGHT_TRAVEL_START_KST_DATE
    ,  F.FLIGHT_PURPOSE_TYPE
  FROM (
SELECT C.TRAVEL_ID
     , MIN(C.RESVE_ID) AS FLIGHT_RESVE_ID
  FROM CREATE_TRAVEL_ID C
  WHERE C.RESVE_ID LIKE 'f%'
  GROUP BY TRAVEL_ID
  ) M
  LEFT JOIN FLIGHT_PURPOSE F ON M.FLIGHT_RESVE_ID = F.RESVE_ID
  LEFT JOIN CREATE_TRAVEL_ID C ON M.FLIGHT_RESVE_ID = C.RESVE_ID
  LEFT JOIN {{ ref('MART_AIR_PNR_SALE_D') }} P ON M.FLIGHT_RESVE_ID = CONCAT('f', P.PNR_NO) AND P.KIND = 1
)
SELECT C.RESVE_ID
    ,  C.USER_ID
    ,  C.TRAVEL_START_KST_DATE
    ,  C.TRAVEL_END_KST_DATE
    ,  C.TRAVEL_ID
    ,  C.TRAVEL_DETAIL_ID
    ,  F.FLIGHT_PURPOSE_TYPE
    ,  IF(C.RESVE_ID NOT LIKE 'f%' AND F.TRAVEL_ID IS NOT NULL, 'Y', 'N') AS INCLUDE_FLIGHT_FLAG
    ,  IF(C.RESVE_ID NOT LIKE 'f%' AND F.CANCEL_FLAG = 'N'
       AND F.CLOSS_SELL_CONDITION_FLAG = 'Y' AND C.USER_ID <> 'smart_guest', 'Y', 'N') AS CROSS_SELL_FLAG
    ,  IF(C.RESVE_ID NOT LIKE 'f%', F.FLIGHT_RESVE_ID, null) AS FLIGHT_RESVE_ID
    ,  IF(C.RESVE_ID NOT LIKE 'f%', F.FLIGHT_CREATE_KST_DT, null) AS FLIGHT_CREATE_KST_DT
    ,  IF(C.RESVE_ID NOT LIKE 'f%', F.FLIGHT_TRAVEL_START_KST_DATE, null) AS FLIGHT_TRAVEL_START_KST_DATE
    ,  IF(C.RESVE_ID NOT LIKE 'f%', DATE_DIFF(C.CREATE_KST_DT, F.FLIGHT_CREATE_KST_DT, DAY), null) AS FLIGHT_TO_RESV_DATE_DIFF_VALUE
    ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
  FROM CREATE_TRAVEL_ID C
  LEFT JOIN FLIGHT_RESVE_INFORMATION F ON C.TRAVEL_ID = F.TRAVEL_ID