{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_AIR_PNR_SALE_D',
        partition_by={
            'field': 'BASIS_DATE',
            'data_type': 'date',
            'granularity': 'month'
        },
        cluster_by=['SALE_FORM_CD', 'KIND']
    )
}}

SELECT A.BASIS_DATE
    ,  A.PNR_NO
    ,  A.KIND
    ,  A.SUPER_PNR_NO
    ,  A.ALPHA_PNR_NO
    ,  A.OLD_PNR_NO
    ,  A.ON_OFF_RESVE_FLAG
    ,  A.SPLIT_SEARCH_FLAG
    ,  A.GDS_CD
    ,  A.AIRLINE_CD
    ,  A.STOCK_AIRLINE_CD
    ,  A.SALE_FORM_CD
    ,  A.SALE_FORM_TYPE
    ,  MIN_BY(A.SALE_AGG_TYPE, CASE A.SALE_AGG_TYPE WHEN 'B2C_ON' THEN 1
                                                    WHEN 'PACKAGE' THEN 2
                                                    WHEN 'AGENCY' THEN 3
                                                    WHEN 'CUSTOMIZED' THEN 4
                                                    WHEN 'EMPLOYEE' THEN 5
                                                    WHEN 'CORPORATION' THEN 6
                                                    WHEN 'CUSTOMIZED' THEN 7
                                                    ELSE 999 END) AS SALE_AGG_TYPE
    ,  A.BRANCH_CD
    ,  A.IND_GROUP_FLAG
    ,  A.USER_ID
    ,  A.SEAT_CNT
    ,  A.FARE_CONFIRM_FLAG
    ,  A.FARE_KIND_CD
    ,  A.FARE_KIND_DETAIL_CD
    ,  A.BPLC_CD
    ,  A.RESVE_SEAT_GRADE
    ,  A.RESVE_KST_DT
    ,  CASE WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN S.dep_dtm
            ELSE A.DEPART_KST_DT END AS DEPART_KST_DT -- 국내선 왕편의 출발일을 왕복편의 출발일로 지정
    ,  CASE WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO < SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN S.dep_dtm
            WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN A.DEPART_KST_DT
            ELSE A.RETURN_KST_DT END AS RETURN_KST_DT-- 국내선 복편의 출발일을 왕복편 모두 귀국일로 지정
    ,  A.TRIP_TYPE_CD AS TRIP_TYPE_CD
    ,  CASE WHEN A.PNR_NO < SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN '1'
            WHEN A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN '2'
            ELSE NULL END AS ITIN_NO
    ,  A.RESVE_STATUS_CD
    ,  A.PAYMENT_STATUS_CD
    ,  A.AUTO_ISSUE_FLAG
    ,  A.ISSUE_KST_DATE
    ,  A.CANCEL_KST_DT
    ,  A.TOTAL_ITIN_CONTENT
    ,  A.DOMESTIC_INTERNATIONAL_DIV_CD
    ,  A.LOC_ROUTE_CD
    ,  A.DEPART_CITY_FLAG
    ,  A.DEPART_CITY_CD
    ,  A.ARRIVE_COUNTRY_CD
    ,  A.ARRIVE_CITY_CD
    ,  A.ARRIVE_AIRPORT_CD
    ,  A.PAYMENT_PLATFORM
    ,  A.PAYMENT_METHOD_CD
    ,  CASE WHEN SUM(IFNULL(A.PROMO_ID, 0)) > 0 THEN 'Y'
            WHEN SUM(IFNULL(A.PROMO_ID, 0)) = 0 THEN 'N'
            ELSE NULL END AS PROMO_FLAG
    ,  A.MARKETING_PARTNERSHIP_CD
    ,  A.MARKETING_LINK_ID
    ,  A.TRANSIT_FLAG
    ,  A.CODESHARE_FLAG
    ,  A.PACKAGE_RESVE_ID
    ,  SUM(A.DISCOUNT_BEFORE_NET_PRICE) AS DISCOUNT_BEFORE_NET_PRICE
    ,  SUM(A.DISCOUNT_AFTER_NET_PRICE) AS DISCOUNT_AFTER_NET_PRICE
    ,  SUM(A.TAX_PRICE) AS TAX_PRICE
    ,  SUM(A.SALE_QUEUE_PRICE) AS SALE_QUEUE_PRICE
    ,  SUM(A.FUEL_ADD_PRICE) AS FUEL_ADD_PRICE
    ,  SUM(A.TASF_PRICE) AS TASF_PRICE
    ,  SUM(A.SALE_TOTAL_PRICE) AS SALE_TOTAL_PRICE
    ,  SUM(A.FEE_PRICE) AS FEE_PRICE
    ,  SUM(A.FEE_VAT_PRICE) AS FEE_VAT_PRICE
    ,  SUM(A.POINT_PRICE) AS POINT_PRICE
    ,  SUM(A.CHILD_RESVE_TICKET_CNT) AS CHILD_RESVE_PRSNL_CNT
    ,  SUM(A.ADULT_RESVE_TICKET_CNT) AS ADULT_RESVE_PRSNL_CNT
    ,  SUM(A.CHILD_RESVE_TICKET_CNT) + SUM(A.ADULT_RESVE_TICKET_CNT) AS RESVE_PRSNL_CNT
    ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM {{ ref('MART_AIR_SALE_D') }} A
LEFT JOIN {{ source('air', 'TB_AIR_RV100') }} S ON A.PNR_NO = SAFE_CAST(S.super_rsv_no AS INT64)
GROUP BY A.BASIS_DATE
    ,  A.PNR_NO
    ,  A.KIND
    ,  A.SUPER_PNR_NO
    ,  A.ALPHA_PNR_NO
    ,  A.OLD_PNR_NO
    ,  A.ON_OFF_RESVE_FLAG
    ,  A.SPLIT_SEARCH_FLAG
    ,  A.GDS_CD
    ,  A.AIRLINE_CD
    ,  A.STOCK_AIRLINE_CD
    ,  A.SALE_FORM_CD
    ,  A.SALE_FORM_TYPE
    ,  A.BRANCH_CD
    ,  A.IND_GROUP_FLAG
    ,  A.USER_ID
    ,  A.SEAT_CNT
    ,  A.FARE_CONFIRM_FLAG
    ,  A.FARE_KIND_CD
    ,  A.FARE_KIND_DETAIL_CD
    ,  A.BPLC_CD
    ,  A.RESVE_SEAT_GRADE
    ,  A.RESVE_KST_DT
    ,  CASE WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN S.dep_dtm
            ELSE A.DEPART_KST_DT END
    ,  CASE WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO < SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN S.dep_dtm
            WHEN A.DOMESTIC_INTERNATIONAL_DIV_CD = 'D' AND A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN A.DEPART_KST_DT
            ELSE A.RETURN_KST_DT END
    ,  A.TRIP_TYPE_CD
    ,  CASE WHEN A.PNR_NO < SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN '1'
            WHEN A.PNR_NO > SAFE_CAST(A.SUPER_PNR_NO AS INT64) THEN '2'
            ELSE NULL END
    ,  A.RESVE_STATUS_CD
    ,  A.PAYMENT_STATUS_CD
    ,  A.AUTO_ISSUE_FLAG
    ,  A.ISSUE_KST_DATE
    ,  A.CANCEL_KST_DT
    ,  A.TOTAL_ITIN_CONTENT
    ,  A.DOMESTIC_INTERNATIONAL_DIV_CD
    ,  A.LOC_ROUTE_CD
    ,  A.DEPART_CITY_FLAG
    ,  A.DEPART_CITY_CD
    ,  A.ARRIVE_COUNTRY_CD
    ,  A.ARRIVE_CITY_CD
    ,  A.ARRIVE_AIRPORT_CD
    ,  A.PAYMENT_PLATFORM
    ,  A.PAYMENT_METHOD_CD
    ,  A.MARKETING_PARTNERSHIP_CD
    ,  A.MARKETING_LINK_ID
    ,  A.TRANSIT_FLAG
    ,  A.CODESHARE_FLAG
    ,  A.PACKAGE_RESVE_ID