{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_SALE_D',
        partition_by={
            'field': 'BASIS_DATE',
            'data_type': 'date',
            'granularity': 'month'
        },
        cluster_by=['DOMAIN_NM', 'KIND', 'RECENT_STATUS']
    )
}}

WITH PARTNER_TYPE AS (
SELECT CAST(A.reservation_id AS STRING) AS RESVE_ID
    ,  '2.0 PRODUCT' AS DOMAIN_NM
    ,  A.guide_settle_type AS PARTNER_SETTLE_TYPE
    ,  A.guide_sales_type AS PARTNER_SALES_TYPE
FROM {{ source('mrt_20', 'reservation_additional_attributes') }} A

UNION ALL

SELECT C.reservation_no AS RESVE_ID
     , '3.0 PRODUCT' AS DOMAIN_NM
     , STRING_AGG(DISTINCT LOWER(C.settlement_type), ', ' ORDER BY LOWER(C.settlement_type)) AS PARTNER_SETTLE_TYPE
     , STRING_AGG(DISTINCT LOWER(C.sale_type), ', ' ORDER BY LOWER(C.sale_type)) AS PARTNER_SALES_TYPE
FROM {{ source('settles', 'payment_product_closing') }} C
WHERE C.deleted_at IS NULL
GROUP BY C.reservation_no
),
HOTEL_RESERVUPDATE_DETAIL_NODUP AS (
SELECT H.reserv_id
    ,  H.title
    ,  H.affiliate
    ,  H.campaign
  FROM (
SELECT H.reserv_id
    ,  H.title
    ,  H.affiliate
    ,  H.campaign
    ,  ROW_NUMBER() OVER (PARTITION BY H.reserv_id ORDER BY H.updated_at_kst DESC) RN
 FROM {{ source('localstay', 'hotel_reservupdate_detail') }} H
 ) H
 WHERE H.RN = 1
),
-- 온다 호텔 예약건 맵핑 추가
ONDA_HOTEL_MAPPING AS (
    SELECT DISTINCT
          r.reserv_no AS RESVE_ID
        , r.reserv_created AS CREATE_DT
        , m.vendor_id AS ONDA_VENDOR_ID
        , m.vendor_name AS ONDA_VENDOR_NAME
    FROM {{ source('localstay', 'onda_reservation') }} r
    LEFT JOIN {{ source('localstay', 'onda_supplier_mapping') }} m
        ON r.gds_pid = CAST(m.child_pid AS STRING)
),
-- 숙소 3.0 추가
HOTEL_30_MAPPING AS (
    SELECT DISTINCT
           r.reservation_no AS RESVE_ID
         --, ri.lodging_id AS PRODUCT_ID-- 상품 레벨 아이디. 2022/01/18 기준 예약 번호 : 상품 레벨 아이디 = 1:1
         , l.vendor_id AS ONDA_VENDOR_ID
         , l.vendor_name AS ONDA_VENDOR_NAME
    FROM {{ source('localstay', 'reservation') }} r
    LEFT JOIN {{ source('localstay', 'reservation_item') }} ri ON r.reservation_id = ri.reservation_id
    LEFT JOIN {{ source('localstay', 'lodging') }} l ON ri.lodging_id = l.lodging_id
),
-- AIRBRIDGE의 UTM의 경우, 하나의 ORDER_ID에 여러 개의 RESVE_ID가 있을 때 RESVE_ID에 하나라도 UTM 정보가 있다면 모든 RESVE_ID에 적용
AIRBRIDGE_CORRECTION AS (
    SELECT S.ORDER_ID
        ,  MAX(A.FIRST_UTM_MEDIUM) AS FIRST_UTM_MEDIUM
        ,  MAX(A.FIRST_UTM_SOURCE) AS FIRST_UTM_SOURCE
        ,  MAX(A.FIRST_UTM_CAMPAIGN) AS FIRST_UTM_CAMPAIGN
        ,  MAX(A.FIRST_UTM_TERM) AS FIRST_UTM_TERM
        ,  MAX(A.FIRST_UTM_CONTENT) AS FIRST_UTM_CONTENT
        ,  MAX(A.UTM_MEDIUM) AS UTM_MEDIUM
        ,  MAX(A.UTM_SOURCE) AS UTM_SOURCE
        ,  MAX(A.UTM_CAMPAIGN) AS UTM_CAMPAIGN
        ,  MAX(A.UTM_TERM) AS UTM_TERM
        ,  MAX(A.UTM_CONTENT) AS UTM_CONTENT
        ,  MAX(A.N_AD) AS N_AD
        ,  MAX(A.N_AD_GROUP) AS N_AD_GROUP
        ,  MAX(A.N_CAMPAIGN_TYPE) AS N_CAMPAIGN_TYPE
        ,  MAX(A.N_KEYWORD) AS N_KEYWORD
        ,  MAX(A.N_KEYWORD_ID) AS N_KEYWORD_ID
        ,  MAX(A.MRT_CONTENTS_VALUE) AS MRT_CONTENTS_VALUE
      FROM {{ ref('INT_SALE_BASE_D') }} S
      LEFT JOIN {{ ref('MART_RESVE_ATTRIBUTE_D') }} A ON A.RESVE_ID = S.RESVE_ID
    WHERE S.KIND = 1
      AND A.DOMAIN_NM = 'AIRBRIDGE'
    GROUP BY S.ORDER_ID
),
REGION_TNA_MAPPING AS (
    SELECT
        CITY_NM_KEY
      , COUNTRY_NM_KEY
      , REGION_NM_KEY
      , REGION_TNA_NM
    FROM {{ ref('INT_REGION_TNA_MAPPING_KEY') }}
)
SELECT S.BASIS_DATE AS BASIS_DATE
    ,  S.RESVE_ID AS RESVE_ID
    ,  S.ORDER_ID AS ORDER_ID
    ,  S.ORDER_NO AS ORDER_NO
    ,  S.USER_ID AS USER_ID
    ,  S.KIND AS KIND
    ,  S.RECENT_STATUS AS RECENT_STATUS
    ,  S.DOMAIN_NM AS DOMAIN_NM
    ,  S.PRODUCT_ID AS PRODUCT_ID
    ,  S.GID AS GID
    ,  S.GPID AS GPID
    ,  CASE WHEN S.DOMAIN_NM IN ('AIR', 'INSURANCE') THEN NULL
            WHEN S.DOMAIN_NM = 'HOTEL' THEN H.title
            WHEN S.DOMAIN_NM = '2.0 PRODUCT' THEN O.title
            WHEN S.DOMAIN_NM = '3.0 PRODUCT' THEN R.product_title
            END AS PRODUCT_TITLE
    ,  S.CONFIRM_KST_DT AS CONFIRM_KST_DT
    ,  CAST(S.CONFIRM_KST_DT AS DATE) AS CONFIRM_KST_DATE
    ,  CAST(S.CREATE_KST_DT AS DATE) AS CREATE_KST_DATE
    ,  S.CANCEL_KST_DT AS CANCEL_KST_DT
    ,  S.TRAVEL_START_KST_DATE AS TRAVEL_START_KST_DATE
    ,  S.TRAVEL_END_KST_DATE AS TRAVEL_END_KST_DATE
    ,  DATE_DIFF(S.TRAVEL_START_KST_DATE, CAST(S.CREATE_KST_DT AS DATE), DAY) AS RESV_TO_START_DATE_DIFF_VALUE
    ,  S.RESVE_TYPE AS RESVE_TYPE
    ,  S.ORDER_RESVE_TYPE AS ORDER_RESVE_TYPE
    ,  CASE WHEN S.DOMAIN_NM IN ('AIR') AND S.SALE_FORM_CD IN ('B2B', 'B2BON') THEN 'B2B'
            WHEN S.DOMAIN_NM IN ('2.0 PRODUCT', '3.0 PRODUCT') THEN S.SALE_FORM_CD
            ELSE CASE WHEN SC.LV_1_CD = 'PACKAGE' OR (SC.LV_1_CD = 'ORDER_MADE' AND SC.LV_2_CD NOT IN ('KIDS_ORDER_MADE')) THEN 'B2B'
                      WHEN SC.LV_3_CD IN ('B2B_ACCOMMODATION_V2') THEN 'B2B'
                      ELSE 'B2C' END END AS SALE_FORM_CD
    ,  S.SALE_FORM_TYPE AS SALE_FORM_TYPE
    ,  S.SALE_AGG_TYPE AS SALE_AGG_TYPE
    ,  S.BRANCH_CD AS BRANCH_CD
    ,  R.product_category AS CATEGORY_NM
    ,  CD.CATEGORY_ID AS CATEGORY_ID
    ,  CD.CATEGORY_CD AS CATEGORY_CD
    ,  CD.SUB_CATEGORY_ID AS SUB_CATEGORY_ID
    ,  CD.SUB_CATEGORY_CD AS SUB_CATEGORY_CD
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_1_CD, SC2.LV_1_CD) END AS STANDARD_CATEGORY_LV_1_CD
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_1_NM, SC2.LV_1_NM) END AS STANDARD_CATEGORY_LV_1_NM
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_2_CD, SC2.LV_2_CD) END AS STANDARD_CATEGORY_LV_2_CD
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_2_NM, SC2.LV_2_NM) END AS STANDARD_CATEGORY_LV_2_NM
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_3_CD, SC2.LV_3_CD) END AS STANDARD_CATEGORY_LV_3_CD
    ,  CASE WHEN S.DOMAIN_NM = 'AIR ANCILLARY' THEN 'AIR_ANCILLARY' ELSE IFNULL(SC.LV_3_NM, SC2.LV_3_NM) END AS STANDARD_CATEGORY_LV_3_NM
    ,  PT.MRT_TYPE AS MRT_TYPE
    ,  PT.TEAM_DIVISION AS TEAM_DIVISION
    ,  S.PG_NM AS PG_NM
    ,  S.RESVE_PAID_KST_DT AS RESVE_PAID_KST_DT
    ,  S.SALES_PRICE AS SALES_PRICE
    ,  S.SALES_PRICE_CUR_TYPE AS SALES_PRICE_CUR_TYPE
    ,  S.SALES_KRW_PRICE AS SALES_KRW_PRICE
    ,  S.COMMISSION_RATE AS COMMISSION_RATE
    ,  S.COMMISSION_PRICE AS COMMISSION_PRICE
    ,  S.SETTLEMENT_COMMISSION_PRICE AS SETTLEMENT_COMMISSION_PRICE
    ,  S.SETTLEMENT_COMMISSION_RATE AS SETTLEMENT_COMMISSION_RATE
    ,  S.PAID_PRICE AS PAID_PRICE
    ,  S.PAID_PRICE_CUR_TYPE AS PAID_PRICE_CUR_TYPE
    ,  S.PAID_KRW_PRICE AS PAID_KRW_PRICE
    ,  S.COUPON_PRICE AS COUPON_PRICE
    ,  S.PRODUCT_COUPON_PRICE AS PRODUCT_COUPON_PRICE
    ,  S.ORDER_COUPON_PRICE AS ORDER_COUPON_PRICE
    ,  S.PRODUCT_COUPON_ID AS PRODUCT_COUPON_ID
    ,  S.ORDER_COUPON_ID AS ORDER_COUPON_ID
    ,  S.POINT_PRICE AS POINT_PRICE
    ,  S.DISCOUNT_PRICE AS DISCOUNT_PRICE
    ,  S.PARTNER_ID AS PARTNER_ID
    ,  S.PAYMENT_LATER_FLAG AS PAYMENT_LATER_FLAG
    ,  S.PAYMENT_LIMIT_KST_DT AS PAYMENT_LIMIT_KST_DT
    ,  S.PARTNERSHIP_CD AS PARTNERSHIP_CD
    ,  S.PARTNERSHIP_TYPE AS PARTNERSHIP_TYPE
    ,  S.MARKETING_PARTNERSHIP_CD AS MARKETING_PARTNERSHIP_CD
    ,  S.MARKETING_LINK_ID AS MARKETING_LINK_ID
    ,  S.PARTNERSHIP_PARTNER_ID AS PARTNERSHIP_PARTNER_ID
    ,  S.PROVIDER_CD AS PROVIDER_CD
    ,  S.CITY_CD AS CITY_CD
    ,  S.CITY_REPRESENTATIVE_FLAG AS CITY_REPRESENTATIVE_FLAG
    ,  CT.CITY AS CITY_NM
    ,  CT.COUNTRY AS COUNTRY_NM
    ,  CT.REGION AS REGION_NM
    ,  M.REGION_TNA_NM AS REGION_TNA_NM
    ,  S.RESVE_PURPOSE_TYPE AS RESVE_PURPOSE_TYPE
    ,  S.CHILD_RESVE_PRSNL_CNT AS CHILD_RESVE_PRSNL_CNT
    ,  S.ADULT_RESVE_PRSNL_CNT AS ADULT_RESVE_PRSNL_CNT
    ,  S.RESVE_PRSNL_CNT AS RESVE_PRSNL_CNT
    ,  S.PLATFORM AS PLATFORM
    ,  IFNULL(RA.FIRST_UTM_MEDIUM, AC.FIRST_UTM_MEDIUM) AS FIRST_RESVE_UTM_MEDIUM
    ,  IFNULL(RA.FIRST_UTM_SOURCE, AC.FIRST_UTM_SOURCE) AS FIRST_RESVE_UTM_SOURCE
    ,  IFNULL(RA.FIRST_UTM_CAMPAIGN, AC.FIRST_UTM_CAMPAIGN) AS FIRST_RESVE_UTM_CAMPAIGN
    ,  IFNULL(RA.FIRST_UTM_TERM, AC.FIRST_UTM_TERM) AS FIRST_RESVE_UTM_TERM
    ,  IFNULL(RA.FIRST_UTM_CONTENT, AC.FIRST_UTM_CONTENT) AS FIRST_RESVE_UTM_CONTENT
    ,  IFNULL(RA.UTM_MEDIUM, AC.UTM_MEDIUM) AS RESVE_UTM_MEDIUM
    ,  IFNULL(RA.UTM_SOURCE, AC.UTM_SOURCE) AS RESVE_UTM_SOURCE
    ,  IFNULL(RA.UTM_CAMPAIGN, AC.UTM_CAMPAIGN) AS RESVE_UTM_CAMPAIGN
    ,  IFNULL(RA.UTM_TERM, AC.UTM_TERM) AS RESVE_UTM_TERM
    ,  IFNULL(RA.UTM_CONTENT, AC.UTM_CONTENT) AS RESVE_UTM_CONTENT
    ,  IFNULL(RA.N_AD, AC.N_AD) AS RESVE_N_AD
    ,  IFNULL(RA.N_AD_GROUP, AC.N_AD_GROUP) AS RESVE_N_AD_GROUP
    ,  IFNULL(RA.N_CAMPAIGN_TYPE, AC.N_CAMPAIGN_TYPE) AS RESVE_N_CAMPAIGN_TYPE
    ,  IFNULL(RA.N_KEYWORD, AC.N_KEYWORD) AS RESVE_N_KEYWORD
    ,  IFNULL(RA.N_KEYWORD_ID, AC.N_KEYWORD_ID) AS RESVE_N_KEYWORD_ID
    ,  IFNULL(RA.MRT_CONTENTS_VALUE, AC.MRT_CONTENTS_VALUE) AS RESVE_MRT_CONTENTS_VALUE
    ,  C.TRAVEL_ID AS TRAVEL_ID
    ,  C.TRAVEL_DETAIL_ID AS TRAVEL_DETAIL_ID
    ,  C.CROSS_SELL_FLAG AS CROSS_SELL_FLAG
    ,  C.FLIGHT_PURPOSE_TYPE AS FLIGHT_PURPOSE_TYPE
    ,  C.INCLUDE_FLIGHT_FLAG AS INCLUDE_FLIGHT_FLAG
    ,  C.FLIGHT_RESVE_ID AS FLIGHT_RESVE_ID
    ,  C.FLIGHT_CREATE_KST_DT AS FLIGHT_CREATE_KST_DT
    ,  C.FLIGHT_TRAVEL_START_KST_DATE AS FLIGHT_TRAVEL_START_KST_DATE
    ,  C.FLIGHT_TO_RESV_DATE_DIFF_VALUE AS FLIGHT_TO_RESV_DATE_DIFF_VALUE
    ,  A.sale_form_cd AS FLIGHT_SALE_FORM_CD
    ,  A.ind_grp_flag AS FLIGHT_IND_GROUP_FLAG
    ,  T.PARTNER_SETTLE_TYPE AS PARTNER_SETTLE_TYPE
    ,  T.PARTNER_SALES_TYPE AS PARTNER_SALES_TYPE
    -- 온다 호텔 추가
    ,  CASE
            WHEN S.DOMAIN_NM = 'HOTEL' THEN H.affiliate
            WHEN (S.DOMAIN_NM = '2.0 PRODUCT' AND S.RESVE_TYPE = 'hotel' AND OH.ONDA_VENDOR_ID = 84 )
                OR (S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'accommodation' AND R.product_category IN ('HOTEL', 'RESORT', 'CONDOMINIUM', 'RESIDENCE') AND H3.ONDA_VENDOR_ID = '84')
                OR (S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'accommodation' AND S.STANDARD_CATEGORY_LV_2_CD IN ('HOTELS', 'RESORTS', 'HOSTELS', 'APARTMENTS', 'MOTELS') AND H3.ONDA_VENDOR_ID = '84')
               THEN 'mrt'
            WHEN (S.DOMAIN_NM = '2.0 PRODUCT' AND S.RESVE_TYPE = 'hotel')
                OR (S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'accommodation'  AND R.product_category IN ('HOTEL', 'RESORT', 'CONDOMINIUM', 'RESIDENCE'))
                OR (S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'accommodation'  AND S.STANDARD_CATEGORY_LV_2_CD IN ('HOTELS', 'RESORTS', 'HOSTELS','APARTMENTS', 'MOTELS') AND H3.ONDA_VENDOR_ID IS NOT NULL AND H3.ONDA_VENDOR_ID != '84')
               THEN 'onda'
           ELSE NULL END AS HOTEL_AFFILIATE_NM
    ,  H.CAMPAIGN AS HOTEL_CAMPAIGN_ID
    ,  S.PACKAGE_PNR_NO AS PACKAGE_PNR_NO
    ,  S.CREATE_KST_DT AS CREATE_KST_DT
    ,  S.UPDATE_KST_DT AS UPDATE_KST_DT
    ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
  FROM {{ ref('INT_SALE_BASE_D') }} S
  LEFT JOIN {{ source('air', 'TB_AIR_RV100') }} A ON S.RESVE_ID = CONCAT('f', A.pnr_seqno) AND S.DOMAIN_NM = 'AIR'
  LEFT JOIN HOTEL_RESERVUPDATE_DETAIL_NODUP H ON S.RESVE_ID = CONCAT('h', H.reserv_id) AND S.DOMAIN_NM = 'HOTEL'
  LEFT JOIN {{ source('mrt_20', 'offers') }} O ON S.PRODUCT_ID = CAST(O.ID AS STRING) AND S.DOMAIN_NM = '2.0 PRODUCT'
  LEFT JOIN {{ source('orders', 'reservations') }} R ON S.RESVE_ID = CAST(R.reservation_no AS STRING) AND S.DOMAIN_NM = '3.0 PRODUCT'
  LEFT JOIN {{ ref('DIM_CROSS_SELL') }} C ON S.RESVE_ID = C.RESVE_ID
  LEFT JOIN {{ source('ups', 'union_product_v3') }} UPS ON S.GID = CAST(UPS.id AS STRING)
  /* FIXME: UPS standard_category_code 'PICKUP_SENDINGS'(복수형) vs dim_standard_category 'PICKUP_SENDING'(단수형) 불일치 임시 보정.
     원천(union_product_v3 id=3859885) 수정 완료 후 CASE 제거하고 원래 조인으로 복원할 것. */
  LEFT JOIN {{ source('mrt_mart_view','dim_standard_category') }} SC
    ON CASE WHEN UPS.standard_category_code = 'PICKUP_SENDINGS' THEN 'PICKUP_SENDING'
            ELSE UPS.standard_category_code
       END = SC.LV_3_CD
  LEFT JOIN {{ ref('DIM_PRODUCT_CATEGORY') }} CD ON S.PRODUCT_ID = CD.PRODUCT_ID
                                             AND (S.DOMAIN_NM = '2.0 PRODUCT' OR (S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'touractivity'))
  LEFT JOIN PARTNER_TYPE T ON S.RESVE_ID = T.RESVE_ID AND S.DOMAIN_NM = T.DOMAIN_NM
  LEFT JOIN {{ ref('DIM_RESVE_TYPE') }} PT ON S.PRODUCT_ID = PT.PRODUCT_ID AND S.DOMAIN_NM = PT.DOMAIN_NM
  LEFT JOIN {{ ref("DIM_CITY") }} CT ON S.CITY_CD = CT.CODE
  LEFT JOIN REGION_TNA_MAPPING M
    ON CT.CITY = M.CITY_NM_KEY
   AND CT.COUNTRY = M.COUNTRY_NM_KEY
   AND CT.REGION = M.REGION_NM_KEY
  LEFT JOIN {{ ref('MART_RESVE_ATTRIBUTE_D') }} RA ON S.RESVE_ID = RA.RESVE_ID AND RA.DOMAIN_NM <> 'AIRBRIDGE'
  LEFT JOIN AIRBRIDGE_CORRECTION AC ON S.ORDER_ID = AC.ORDER_ID
  -- 온다 호텔 맵핑 추가
  LEFT JOIN ONDA_HOTEL_MAPPING OH ON S.RESVE_ID = OH.RESVE_ID AND S.DOMAIN_NM = '2.0 PRODUCT' AND S.RESVE_TYPE = 'hotel'
  -- 숙소 3.0 추가
  LEFT JOIN HOTEL_30_MAPPING H3 ON S.RESVE_ID = H3.RESVE_ID AND S.DOMAIN_NM = '3.0 PRODUCT' AND S.RESVE_TYPE = 'accommodation'
  -- 기존 UPS 테이블로 STANDARD_CATEGORY 채워넣기
  LEFT JOIN {{ ref('DW_MRT_UPS_UNION_PRODUCT_NODUP') }} N ON R.product_id = N.PRODUCT_NO
  LEFT JOIN {{ source('ups', 'union_product_v3') }} UPS2 ON N.PRODUCT_ID = CAST(UPS2.id AS STRING)
  LEFT JOIN {{ source('mrt_mart_view','dim_standard_category') }} SC2 ON UPS2.standard_category_code = SC2.LV_3_CD
