{{
    config(
        materialized = 'incremental',
        schema='braze',
        alias='MART_MKT_BRAZE_ATTRIBUTES',
        pre_hook=[
        "DELETE FROM {{ this }} B WHERE B.USER_ID IN
            (SELECT U.USER_ID FROM {{ ref('DAILY_UPDATE_ATTRIBUTE') }} U WHERE U.BASIS_DT = '{{ var('logical_start_date_kst') }}')"
        ],
        post_hook=[
        "DELETE FROM {{ this }} U WHERE U.EXCLUDED_USER = 'Y'"
        ]

    )
}}

SELECT U.USER_ID
     , U.EXCLUDED_USER
     , U.JOIN_KST_DT
     , U.USERNAME
     , U.MRT_STAFF_FLAG
     , U.REP_AGE
     , U.EMAIL
     , U.PHONE_NUMBER
     , U.APP_INSTALL_FLAG
     , U.SMS_RECV_AGREE
     , U.MAIL_RECV_AGREE
     , U.PUSH_RECV_AGREE
     , U.PHONE_VALID_FLAG
     , U.DORMANT_FLAG
     , U.DORMANT_KST_DT
     , U.LEAVE_FLAG
     , U.LEAVE_KST_DT
     , U.OWN_COUPON_NO
     , U.OWN_COUPON_CNT
     , U.COUPON_SIGNUP_EXPIRE_DATE
     , U.COUPON_REVIEW_EXPIRE_DATE
     , U.COUPON_FIRST_REVIEW_EXPIRE_DATE
     , U.TOTAL_BUY_CNT
     , U.TOTAL_BUY_PRICE
     , U.FIRST_BUY_KST_DT
     , U.FIRST_BUY_TYPE
     , U.RECENT_TRAVEL_RESVE_ID
     , U.RECENT_TRAVEL_PRODUCT_ID
     , U.RECENT_TRAVEL_MRT_TYPE
     , U.RECENT_TRAVEL_DEPART_KST_DT
     , U.RECENT_TRAVEL_ARRIVE_KST_DT
     , U.RECENT_TRAVEL_RESVE_PURPOSE
     , U.RECENT_TRAVEL_CITY
     , U.RECENT_TRAVEL_COUNTRY
     , U.RECENT_TRAVEL_STANDARD_CATEGORY_LV_1_CD
     , U.RECENT_TRAVEL_STANDARD_CATEGORY_LV_2_CD
     , U.RECENT_TRAVEL_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_TRAVEL_RESVE_ID
     , U.EXPT_TRAVEL_PRODUCT_ID
     , U.EXPT_TRAVEL_MRT_TYPE
     , U.EXPT_TRAVEL_DEPART_KST_DT
     , U.EXPT_TRAVEL_ARRIVE_KST_DT
     , U.EXPT_TRAVEL_RESVE_PURPOSE
     , U.EXPT_TRAVEL_CITY
     , U.EXPT_TRAVEL_COUNTRY
     , U.EXPT_TRAVEL_STANDARD_CATEGORY_LV_1_CD
     , U.EXPT_TRAVEL_STANDARD_CATEGORY_LV_2_CD
     , U.EXPT_TRAVEL_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_FLIGHT_TRAVEL_RESVE_ID
     , U.EXPT_FLIGHT_TRAVEL_PRODUCT_ID
     , U.EXPT_FLIGHT_TRAVEL_MRT_TYPE
     , U.EXPT_FLIGHT_TRAVEL_AIRLINE_CD
     , U.EXPT_FLIGHT_TRAVEL_DEPART_KST_DATE
     , U.EXPT_FLIGHT_TRAVEL_ARRIVE_KST_DATE
     , U.EXPT_FLIGHT_TRAVEL_RESVE_PURPOSE
     , U.EXPT_FLIGHT_TRAVEL_CITY
     , U.EXPT_FLIGHT_TRAVEL_COUNTRY
     , U.EXPT_FLIGHT_TRAVEL_RESVE_DATE
     , U.EXPT_FLIGHT_TRAVEL_DEPART_AIRPORT
     , U.EXPT_FLIGHT_TRAVEL_ARRIVE_AIRPORT
     , U.EXPT_FLIGHT_SEAT_GRAD
     , U.EXPT_FLIGHT_USER_AGE
     , U.EXPT_FLIGHT_USER_GENDER
     , U.EXPT_STAY_TRAVEL_RESVE_ID
     , U.EXPT_STAY_TRAVEL_PRODUCT_ID
     , U.EXPT_STAY_TRAVEL_MRT_TYPE
     , U.EXPT_STAY_TRAVEL_DEPART_KST_DATE
     , U.EXPT_STAY_TRAVEL_ARRIVE_KST_DATE
     , U.EXPT_STAY_TRAVEL_RESVE_PURPOSE
     , U.EXPT_STAY_TRAVEL_CITY
     , U.EXPT_STAY_TRAVEL_COUNTRY
     , U.HOTEL_AFFILIATE_NM
     , U.EXPT_STAY_TRAVEL_RESVE_DATE
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_1_CD
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_1_NM
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_2_CD
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_2_NM
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_STAY_STANDARD_CATEGORY_LV_3_NM
     , U.EXPT_RIDE_TRAVEL_RESVE_ID
     , U.EXPT_RIDE_TRAVEL_PRODUCT_ID
     , U.EXPT_RIDE_TRAVEL_MRT_TYPE
     , U.EXPT_RIDE_TRAVEL_DEPART_KST_DATE
     , U.EXPT_RIDE_TRAVEL_ARRIVE_KST_DATE
     , U.EXPT_RIDE_TRAVEL_RESVE_PURPOSE
     , U.EXPT_RIDE_TRAVEL_CITY
     , U.EXPT_RIDE_TRAVEL_COUNTRY
     , U.EXPT_RIDE_TRAVEL_RESVE_DATE
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_1_CD
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_1_NM
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_2_CD
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_2_NM
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_RIDE_STANDARD_CATEGORY_LV_3_NM
     , U.EXPT_TNA_TRAVEL_RESVE_ID
     , U.EXPT_TNA_TRAVEL_PRODUCT_ID
     , U.EXPT_TNA_TRAVEL_MRT_TYPE
     , U.EXPT_TNA_TRAVEL_DEPART_KST_DATE
     , U.EXPT_TNA_TRAVEL_ARRIVE_KST_DATE
     , U.EXPT_TNA_TRAVEL_RESVE_PURPOSE
     , U.EXPT_TNA_TRAVEL_CITY
     , U.EXPT_TNA_TRAVEL_COUNTRY
     , U.EXPT_TNA_TRAVEL_RESVE_DATE
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_1_CD
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_1_NM
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_2_CD
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_2_NM
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_TNA_STANDARD_CATEGORY_LV_3_NM
     , U.EXPT_ETC_TRAVEL_RESVE_ID
     , U.EXPT_ETC_TRAVEL_PRODUCT_ID
     , U.EXPT_ETC_TRAVEL_MRT_TYPE
     , U.EXPT_ETC_TRAVEL_DEPART_KST_DATE
     , U.EXPT_ETC_TRAVEL_ARRIVE_KST_DATE
     , U.EXPT_ETC_TRAVEL_RESVE_PURPOSE
     , U.EXPT_ETC_TRAVEL_CITY
     , U.EXPT_ETC_TRAVEL_COUNTRY
     , U.EXPT_ETC_TRAVEL_RESVE_DATE
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_1_CD
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_1_NM
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_2_CD
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_2_NM
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_3_CD
     , U.EXPT_ETC_STANDARD_CATEGORY_LV_3_NM
     , U.GIFTCARD_SUCCESS_CNT
     , U.GRADE_CD
     , U.CURRENT_MILEAGE_PRICE
     , U.DW_LOAD_DT
  FROM {{ ref('DAILY_UPDATE_ATTRIBUTE') }} U
 WHERE U.BASIS_DT = '{{ var("logical_start_date_kst") }}'
