{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_OPTION_SALE_D'
    )
}}

{% set option_models = [
    'INT_OPTION_SALE_AIR',
    'INT_OPTION_SALE_TNA',
    'INT_OPTION_SALE_STAY',
    'INT_OPTION_SALE_PACKAGE',
    'INT_OPTION_SALE_OVERSEAS_RENTALCAR',
    'INT_OPTION_SALE_INSURANCE',
    'INT_OPTION_SALE_LEGACY'
] %}

WITH OPTION_SALE_UNION AS (
{% for m in option_models %}
SELECT
    T.*
FROM {{ ref(m) }} T
{% if not loop.last %}UNION ALL{% endif %}
{% endfor %}
)
SELECT
    T.BASIS_DATE AS BASIS_DATE
  , T.RESVE_ID AS RESVE_ID
  , T.RESVE_OPTION_ID AS RESVE_OPTION_ID
  , T.USER_ID AS USER_ID
  , T.ORDER_ID AS ORDER_ID
  , T.KIND AS KIND
  , T.PRODUCT_ID AS PRODUCT_ID
  , T.OPTION_ID AS OPTION_ID
  , T.GID AS GID
  , T.OPTION_GID AS OPTION_GID
  , T.DOMAIN_NM AS DOMAIN_NM
  , T.PRODUCT_TITLE AS PRODUCT_TITLE
  , T.OPTION_TITLE AS OPTION_TITLE
  , T.CANCEL_KST_DT AS CANCEL_KST_DT
  , T.RECENT_STATUS AS RECENT_STATUS
  , T.TRAVEL_START_KST_DATE AS TRAVEL_START_KST_DATE
  , T.TRAVEL_END_KST_DATE AS TRAVEL_END_KST_DATE
  , T.PG_NM AS PG_NM
  , T.PLATFORM AS PLATFORM
  , T.RESVE_PAID_KST_DT AS RESVE_PAID_KST_DT
  , T.STANDARD_CATEGORY_LV_1_CD AS STANDARD_CATEGORY_LV_1_CD
  , T.STANDARD_CATEGORY_LV_1_NM AS STANDARD_CATEGORY_LV_1_NM
  , T.STANDARD_CATEGORY_LV_2_CD AS STANDARD_CATEGORY_LV_2_CD
  , T.STANDARD_CATEGORY_LV_2_NM AS STANDARD_CATEGORY_LV_2_NM
  , T.STANDARD_CATEGORY_LV_3_CD AS STANDARD_CATEGORY_LV_3_CD
  , T.STANDARD_CATEGORY_LV_3_NM AS STANDARD_CATEGORY_LV_3_NM
  , T.OPTION_PARTNER_ID AS OPTION_PARTNER_ID
  , T.SALES_KRW_PRICE AS SALES_KRW_PRICE
  , T.PAID_PRICE AS PAID_PRICE
  , T.COUPON_PRICE AS COUPON_PRICE
  , T.PRODUCT_COUPON_PRICE AS PRODUCT_COUPON_PRICE
  , T.ORDER_COUPON_PRICE AS ORDER_COUPON_PRICE
  , T.PRODUCT_COUPON_ID AS PRODUCT_COUPON_ID
  , T.ORDER_COUPON_ID AS ORDER_COUPON_ID
  , T.POINT_PRICE AS POINT_PRICE
  , T.PAYMENT_METHOD_VALUE AS PAYMENT_METHOD_VALUE
  , T.PAYMENT_COMMISSION_RATE AS PAYMENT_COMMISSION_RATE
  , T.PAYMENT_COMMISSION_PRICE AS PAYMENT_COMMISSION_PRICE
  , T.SETTLEMENT_COMMISSION_RATE AS SETTLEMENT_COMMISSION_RATE
  , T.SETTLEMENT_COMMISSION_PRICE AS SETTLEMENT_COMMISSION_PRICE
  , T.CITY_NM AS CITY_NM
  , T.COUNTRY_NM AS COUNTRY_NM
  , T.REGION_NM AS REGION_NM
  , T.RESVE_PURPOSE_TYPE AS RESVE_PURPOSE_TYPE
  , T.CREATE_KST_DT AS CREATE_KST_DT
  , T.UPDATE_KST_DT AS UPDATE_KST_DT
  , DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM OPTION_SALE_UNION T
