{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='DIM_PRODUCT_FPNA_TYPE'
    )
}}

WITH ROW_DATA AS (
    SELECT P.GID
        ,  C.LV_1_CD AS STANDARD_CATEGORY_LV_1_CD
        ,  C.LV_2_CD AS STANDARD_CATEGORY_LV_2_CD
        ,  C.LV_3_CD AS STANDARD_CATEGORY_LV_3_CD
        ,  CT.COUNTRY AS COUNTRY_NM
        ,  SP.provider_code AS PROVIDER_CD
        ,  P.PARTNER_ID AS PARTNER_ID
        ,  P.PRODUCT_ID AS PRODUCT_ID
        ,  DT.MRT_TYPE AS MRT_TYPE
        ,  CASE WHEN D.GID IS NOT NULL THEN 'Y' ELSE 'N' END AS DST_FLAG
    FROM {{ ref("MART_PRODUCT_ORIGINAL_D") }} P
    LEFT JOIN {{ ref("DIM_CITY") }} CT ON P.CITY_CD = CT.CODE
    LEFT JOIN {{ source('ups', 'union_product_v3') }} UPS ON P.GID = CAST(UPS.id AS STRING)
    LEFT JOIN {{ source('mrt_mart_view','dim_standard_category') }} C ON UPS.standard_category_code = C.LV_3_CD
    LEFT JOIN {{ source('unionstay', 'property') }} SP ON P.product_id = CAST(SP.property_id AS STRING)
    LEFT JOIN {{ ref("DIM_PRODUCT_TYPE") }} DT ON P.GID = DT.GID
    LEFT JOIN (
      SELECT DISTINCT GID
        FROM {{ ref('FPNA_LODGMENT_DST_TOTAL_INFO') }}
        WHERE DST_STATUS NOT IN ('LOST', 'PITCH') AND DST_STATUS IS NOT NULL AND GID IS NOT NULL
          AND ACCOUNT_TYPE IN ('숙박권', '날짜지정')
    ) D ON P.GID = D.GID
),
BIZTYPE_DATA AS (
    SELECT R.GID AS GID
        ,  CASE WHEN R.STANDARD_CATEGORY_LV_1_CD IN ('ACCOMMODATION') THEN
                CASE WHEN R.STANDARD_CATEGORY_LV_2_CD = 'B2B_ACCOMMODATION' THEN 'B2B_ACCOMMODATION'
                WHEN (R.COUNTRY_NM != 'Korea, Republic of' OR R.COUNTRY_NM IS NULL) AND R.PROVIDER_CD = 'STAYNET' THEN 'OUTBOUND_ACCOMMODATION_STAYNET'
                WHEN (R.MRT_TYPE IN ('lodging') AND (R.COUNTRY_NM != 'Korea, Republic of' OR R.COUNTRY_NM IS NULL)) OR (R.STANDARD_CATEGORY_LV_3_CD = 'LODGING_V2' AND (R.COUNTRY_NM != 'Korea, Republic of' OR R.COUNTRY_NM IS NULL))
                     OR (R.STANDARD_CATEGORY_LV_2_CD = 'MINBAK' AND R.STANDARD_CATEGORY_LV_3_CD = 'KOREAN_MINBAK' AND R.PROVIDER_CD = 'STAYNET') THEN 'KOREAN_LODGING'
                WHEN R.DST_FLAG = 'Y' OR R.STANDARD_CATEGORY_LV_2_CD = 'ACCOMMODATION_TICKET' OR R.PARTNER_ID IN ('21293') OR R.GID IN ('2555714', '1098860') THEN 'DIRECT_SALES_ACCOMMODATION'
                WHEN (R.COUNTRY_NM = 'Korea, Republic of') THEN 'DOMESTIC_ACCOMMODATION'
                WHEN (R.COUNTRY_NM != 'Korea, Republic of' OR R.COUNTRY_NM IS NULL) THEN 'OUTBOUND_ACCOMMODATION' END
          WHEN R.STANDARD_CATEGORY_LV_1_CD IN ('INSURANCE') THEN 'INSURANCE'
          WHEN R.STANDARD_CATEGORY_LV_1_CD IN ('TRANSPORTATION_V2') THEN
               CASE WHEN R.STANDARD_CATEGORY_LV_3_CD = 'EUROPE_TRAIN' THEN 'OUTBOUND_TRAIN_RAILEUROPE'
                    WHEN R.COUNTRY_NM LIKE '%Korea%' THEN 'DOMESTIC_RENTALCAR'
                    ELSE 'OUTBOUND_RENTALCAR' END
          WHEN R.STANDARD_CATEGORY_LV_1_CD IN ('PACKAGE') THEN
               CASE WHEN R.STANDARD_CATEGORY_LV_3_CD = 'PKG_STAY_DOMESTIC' THEN 'PKG_STAY_DOMESTIC'
                    WHEN R.STANDARD_CATEGORY_LV_2_CD = 'PKG_BIZ_STAY' THEN 'PKG_STAY_OUTBOUND'
                    WHEN R.STANDARD_CATEGORY_LV_3_CD = 'PKG_TNA_DOMESTIC' THEN 'PKG_TNA_DOMESTIC'
                    WHEN R.STANDARD_CATEGORY_LV_2_CD = 'PKG_BIZ_TNA' THEN 'PKG_TNA_OUTBOUND'
                    WHEN R.STANDARD_CATEGORY_LV_1_CD = 'ORDER_MADE' THEN 'ORDER_MADE'
                    WHEN R.STANDARD_CATEGORY_LV_1_CD = 'PACKAGE' AND (R.COUNTRY_NM != 'Korea, Republic of' AND R.COUNTRY_NM IS NOT NULL) THEN 'PKG_OTHERS_OUTBOUND'
                    WHEN R.STANDARD_CATEGORY_LV_1_CD = 'PACKAGE' AND (R.COUNTRY_NM = 'Korea, Republic of') THEN 'PKG_OTHERS_DOMESTIC'
                    WHEN (R.COUNTRY_NM != 'Korea, Republic of' AND R.COUNTRY_NM IS NOT NULL) THEN 'OUTBOUND_TNA'
                    WHEN (R.COUNTRY_NM = 'Korea, Republic of') THEN 'DOMESTIC_TNA'
                    ELSE 'PACKAGE_OTHERS' END
          ELSE
              CASE --맞춤여행 & 패키지 구분
                   WHEN R.STANDARD_CATEGORY_LV_1_CD = 'ORDER_MADE' THEN 'ORDER_MADE'
                   WHEN R.STANDARD_CATEGORY_LV_3_CD = 'PKG_STAY_DOMESTIC' THEN 'PKG_STAY_DOMESTIC'
                   WHEN R.STANDARD_CATEGORY_LV_2_CD = 'PKG_BIZ_STAY' THEN 'PKG_STAY_OUTBOUND'
                   WHEN R.STANDARD_CATEGORY_LV_3_CD = 'PKG_TNA_DOMESTIC' THEN 'PKG_TNA_DOMESTIC'
                   WHEN R.STANDARD_CATEGORY_LV_2_CD = 'PKG_BIZ_TNA' THEN 'PKG_TNA_OUTBOUND'
                   WHEN R.STANDARD_CATEGORY_LV_1_CD = 'ORDER_MADE' THEN 'ORDER_MADE'
                   WHEN R.STANDARD_CATEGORY_LV_3_CD = 'ESIM_SUPPLIER' THEN 'OUTBOUND_ESIM_USIM'
                   WHEN R.STANDARD_CATEGORY_LV_1_CD = 'PACKAGE' AND (R.COUNTRY_NM != 'Korea, Republic of' AND R.COUNTRY_NM IS NOT NULL) THEN 'PKG_OTHERS_OUTBOUND'
                   WHEN R.STANDARD_CATEGORY_LV_1_CD = 'PACKAGE' AND (R.COUNTRY_NM = 'Korea, Republic of') THEN 'PKG_OTHERS_DOMESTIC'
               --TNA
                   WHEN (R.PARTNER_ID IN (SELECT DISTINCT CAST(partner_id AS STRING) AS partner_id FROM {{ ref('FPNA_TNA_BIZ_TYPE_INFO') }} WHERE biz_type_partner = 'Commerce') OR R.product_id IN (SELECT DISTINCT CAST(product_id AS STRING) AS product_id FROM {{ ref('FPNA_TNA_BIZ_TYPE_INFO') }} WHERE biz_type_product = 'Commerce')) AND (R.COUNTRY_NM != 'Korea, Republic of' AND R.COUNTRY_NM IS NOT NULL) THEN 'OUTBOUND_COMMERCE'
                   WHEN (R.PARTNER_ID IN (SELECT DISTINCT CAST(partner_id AS STRING) AS partner_id FROM {{ ref('FPNA_TNA_BIZ_TYPE_INFO') }} WHERE biz_type_partner = 'Commerce') OR R.product_id IN (SELECT DISTINCT CAST(product_id AS STRING) AS product_id FROM {{ ref('FPNA_TNA_BIZ_TYPE_INFO') }} WHERE biz_type_product = 'Commerce')) AND (R.COUNTRY_NM = 'Korea, Republic of') THEN 'DOMESTIC_COMMERCE'
                   WHEN (R.COUNTRY_NM != 'Korea, Republic of' AND R.COUNTRY_NM IS NOT NULL) THEN 'OUTBOUND_TNA'
                   WHEN (R.COUNTRY_NM = 'Korea, Republic of') THEN 'DOMESTIC_TNA'
                   ELSE 'ETA' END END AS BIZ_TYPE_V3
    FROM ROW_DATA R
),
FPNA_DISTINCT AS (
    SELECT P.GID
         , P.BIZ_TYPE_V3
         , P.FPNA_TYPE_LV_1
         , P.FPNA_TYPE_LV_2
         , P.FPNA_TYPE_LV_3
    FROM {{ ref("MART_FPNA_NONAIR_PROFIT_D") }} P
    QUALIFY ROW_NUMBER() OVER (PARTITION BY P.GID, P.BIZ_TYPE_V3 ORDER BY P.CREATE_KST_DT DESC) = 1
)
SELECT T.GID
     , T.BIZ_TYPE_V3
     , T.FPNA_TYPE_LV_1
     , T.FPNA_TYPE_LV_2
     , T.FPNA_TYPE_LV_3
FROM (
         SELECT F.GID
              , 1 AS PRIORITY
              , F.BIZ_TYPE_V3
              , F.FPNA_TYPE_LV_1
              , F.FPNA_TYPE_LV_2
              , F.FPNA_TYPE_LV_3
         FROM FPNA_DISTINCT F

         UNION ALL

         SELECT BD.GID AS GID
              , 2 AS PRIORITY
              , BD.BIZ_TYPE_V3 AS BIZ_TYPE_V3
              , TYPE_V3.FPNA_TYPE_LV_1 AS FPNA_TYPE_LV_1
              , TYPE_V3.FPNA_TYPE_LV_2 AS FPNA_TYPE_LV_2
              , TYPE_V3.FPNA_TYPE_LV_3 AS FPNA_TYPE_LV_3
         FROM BIZTYPE_DATA BD
         LEFT JOIN {{ ref('FPNA_TYPE_V3') }} TYPE_V3 ON TYPE_V3.BIZ_TYPE_V3 = BD.BIZ_TYPE_V3
) T
QUALIFY ROW_NUMBER() OVER (PARTITION BY T.GID ORDER BY T.PRIORITY ASC) = 1