{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_HOTEL_PRODUCT_ORIGINAL_D'
    )
}}



SELECT DISTINCT
         '100000002' AS PRODUCT_ID
      ,  'HOTEL' AS DOMAIN_NM
      ,  CAST(NULL AS STRING) AS PRODUCT_NO
      ,  CAST(NULL AS STRING) AS GLOBAL_PRODUCT_ID
      ,  H.title AS PRODUCT_NM
      ,  H.ota_id AS PARTNER_ID
      ,  H.affiliate AS PARTNER_NM
      ,  'hotel' AS PRODUCT_TYPE
      ,  CAST(NULL AS STRING) AS RECENT_STATUS
      ,  'hotel' AS MRT_TYPE
      ,  CAST(NULL AS STRING) AS CATEGORY_CD
      ,  CAST(NULL AS STRING) AS SUB_CATEGORY_CD
      ,  CAST(NULL AS TIMESTAMP) AS CREATE_KST_DT
      ,  CAST(NULL AS TIMESTAMP) AS UPDATE_KST_DT
      ,  CAST(NULL AS TIMESTAMP) AS FIRST_PUBLISHED_KST_DT
      ,  CAST(NULL AS FLOAT64) AS LATITUDE_COORDINATE
      ,  CAST(NULL AS FLOAT64) AS LONGITUDE_COORDINATE
      ,  IFNULL(a.KEY_NM, H.city) AS CITY_CD
      ,  NULL AS COMMISSION_RATE
      ,  CAST(NULL AS STRING) AS DURATION_UNIT
      ,  NULL AS DURATION_SIZE
      ,  CAST(NULL AS BOOL) AS ALLOW_QUICK_RESERVATION
      ,  CAST(NULL AS STRING) AS LOCALE
      ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM {{ source('localstay', 'hotel_reservupdate_detail') }} H
LEFT JOIN {{ ref('DIM_HOTEL_AFFILIATE_CITY_NM') }} a ON a.CITY_NM = H.city AND a.AFFILIATE_NM = H.affiliate