{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_PRODUCT_TOTAL_AGG_D'
    )
}}


SELECT GID AS GID
  ,  SUM(TOTAL_RESERVATION_CNT) AS TOTAL_RESERVATION_CNT
  ,  SUM(TOTAL_SALE_PRICE) AS TOTAL_SALE_PRICE
  ,  MAX(CASE WHEN TOTAL_RESERVATION_CNT > 0 THEN BASIS_DT END) AS LAST_RESVE_KST_DATE
  ,  MIN(CASE WHEN TOTAL_RESERVATION_CNT > 0 THEN BASIS_DT END) AS FIRST_RESVE_KST_DATE
FROM {{ ref('MART_PRODUCT_AGG_D') }}
GROUP BY GID