{{
    config(
        materialized = 'incremental',
        incremental_strategy = 'merge',
        schema='edw_mart',
        alias='MART_USER_HIST_D',
        partition_by={
            'field': 'BASIS_DT',
            'data_type': 'date',
            'granularity': 'day'
        },
        cluster_by = ['USER_ID'],
        pre_hook="DELETE FROM {{ this }} WHERE BASIS_DT = '{{ var('logical_start_date_kst') }}'"
    )
}}

SELECT
    * EXCEPT(
    RECENT_TRAVEL_ORDER_ID
    , RECENT_TRAVEL_RESVE_ID
    , RECENT_TRAVEL_PRODUCT_ID
    , RECENT_TRAVEL_MRT_TYPE
    , RECENT_TRAVEL_DEPART_KST_DT
    , RECENT_TRAVEL_ARRIVE_KST_DT
    , RECENT_TRAVEL_RESVE_PURPOSE
    , RECENT_TRAVEL_CITY
    , RECENT_TRAVEL_COUNTRY
    , EXPT_TRAVEL_ORDER_ID
    , EXPT_TRAVEL_RESVE_ID
    , EXPT_TRAVEL_PRODUCT_ID
    , EXPT_TRAVEL_MRT_TYPE
    , EXPT_TRAVEL_DEPART_KST_DT
    , EXPT_TRAVEL_ARRIVE_KST_DT
    , EXPT_TRAVEL_RESVE_PURPOSE
    , EXPT_TRAVEL_CITY
    , EXPT_TRAVEL_COUNTRY
    , EXPT_FLIGHT_TRAVEL_ORDER_ID
    , EXPT_FLIGHT_TRAVEL_RESVE_ID
    , EXPT_FLIGHT_TRAVEL_PRODUCT_ID
    , EXPT_FLIGHT_TRAVEL_MRT_TYPE
    , EXPT_FLIGHT_TRAVEL_DEPART_KST_DATE
    , EXPT_FLIGHT_TRAVEL_ARRIVE_KST_DT
    , EXPT_FLIGHT_TRAVEL_RESVE_PURPOSE
    , EXPT_FLIGHT_TRAVEL_CITY
    , EXPT_FLIGHT_TRAVEL_COUNTRY
    , EXPT_STAY_TRAVEL_ORDER_ID
    , EXPT_STAY_TRAVEL_RESVE_ID
    , EXPT_STAY_TRAVEL_PRODUCT_ID
    , EXPT_STAY_TRAVEL_MRT_TYPE
    , EXPT_STAY_TRAVEL_DEPART_KST_DATE
    , EXPT_STAY_TRAVEL_ARRIVE_KST_DT
    , EXPT_STAY_TRAVEL_RESVE_PURPOSE
    , EXPT_STAY_TRAVEL_CITY
    , EXPT_STAY_TRAVEL_COUNTRY
    , EXPT_RIDE_TRAVEL_ORDER_ID
    , EXPT_RIDE_TRAVEL_RESVE_ID
    , EXPT_RIDE_TRAVEL_PRODUCT_ID
    , EXPT_RIDE_TRAVEL_MRT_TYPE
    , EXPT_RIDE_TRAVEL_DEPART_KST_DATE
    , EXPT_RIDE_TRAVEL_ARRIVE_KST_DT
    , EXPT_RIDE_TRAVEL_RESVE_PURPOSE
    , EXPT_RIDE_TRAVEL_CITY
    , EXPT_RIDE_TRAVEL_COUNTRY
    , EXPT_TNA_TRAVEL_ORDER_ID
    , EXPT_TNA_TRAVEL_RESVE_ID
    , EXPT_TNA_TRAVEL_PRODUCT_ID
    , EXPT_TNA_TRAVEL_MRT_TYPE
    , EXPT_TNA_TRAVEL_DEPART_KST_DATE
    , EXPT_TNA_TRAVEL_ARRIVE_KST_DT
    , EXPT_TNA_TRAVEL_RESVE_PURPOSE
    , EXPT_TNA_TRAVEL_CITY
    , EXPT_TNA_TRAVEL_COUNTRY
    , EXPT_ETC_TRAVEL_ORDER_ID
    , EXPT_ETC_TRAVEL_RESVE_ID
    , EXPT_ETC_TRAVEL_PRODUCT_ID
    , EXPT_ETC_TRAVEL_MRT_TYPE
    , EXPT_ETC_TRAVEL_DEPART_KST_DATE
    , EXPT_ETC_TRAVEL_ARRIVE_KST_DT
    , EXPT_ETC_TRAVEL_RESVE_PURPOSE
    , EXPT_ETC_TRAVEL_CITY
    , EXPT_ETC_TRAVEL_COUNTRY
    )
FROM {{ ref('MART_USER_D') }}
WHERE UPDATE_KST_DT BETWEEN '{{ var("logical_start_date_kst") }} 00:00:00' AND '{{ var("logical_start_date_kst") }} 23:59:59.999'