{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_USER_D',
        cluster_by = ['USER_ID']
    )
}}

WITH FACT AS (
    SELECT
        * EXCEPT(rn)
    FROM (
        SELECT
             BASIS_DT
            , USER_ID
            , LOGIN_KST_DT
            , LOGIN_PLATFORM
            , ROW_NUMBER() OVER(PARTITION BY USER_ID ORDER BY LOGIN_KST_DT DESC) AS rn
        FROM {{ ref('FACT_USER_LOGIN_D') }}
    ) WHERE rn = 1
),
AIR_USER_INFO AS (
    SELECT
        reg_usr_id AS user_id
        , STRING_AGG(CAST(pax_birth_year AS STRING) ORDER BY MOD(EXTRACT(YEAR FROM CURRENT_DATE) - pax_birth_year, 65) DESC LIMIT 1) AS rep_age
        , STRING_AGG(CASE pax_sex WHEN '1' THEN 'M' WHEN '2' THEN 'F' END LIMIT 1) AS rep_sex
        , STRING_AGG(DISTINCT CONCAT(
            pax_birth_year
            , '-'
            , CASE pax_sex WHEN '1' THEN 'M' WHEN '2' THEN 'F' END
        ) ORDER BY CONCAT(
            pax_birth_year
            , '-'
            , CASE pax_sex WHEN '1' THEN 'M' WHEN '2' THEN 'F' END)
        ) AS ages
        FROM {{ source('air', 'DIM_PREDICTIVE_USR_TB_AIR_RV110') }}
        GROUP BY reg_usr_id
),
COUPON AS (
    SELECT
        CAST(user_id AS STRING) AS user_id
        , COUNT(DISTINCT id) AS total_coupon_cnt
        , COUNT(DISTINCT CASE WHEN used_at IS NULL THEN id END) AS not_used_coupon_cnt
        , COUNT(DISTINCT CASE WHEN used_at IS NOT NULL THEN id END) AS used_coupon_cnt
        , COUNT(DISTINCT CASE WHEN used_at IS NULL AND expire_date >= '{{ var("logical_start_date_kst") }} 00:00:00' THEN id END) AS remain_coupon_cnt
        , STRING_AGG(DISTINCT CASE WHEN used_at IS NULL AND expire_date >= '{{ var("logical_start_date_kst") }} 00:00:00' THEN CAST(template_id AS STRING) END, ",") AS remain_coupon_ids
    FROM {{ source('coupon', 'coupon_user_mapping') }}
    WHERE deleted_at IS NULL
        AND use_status IN ('USE', 'PUBLISHED')
    GROUP BY user_id
)
, REVIEWS AS (
    SELECT
        user_id
        , SUM(review_cnt) AS review_cnt
    FROM (
        SELECT
            CAST(user_id AS STRING) AS user_id
            , COUNT(DISTINCT reservation_id) AS review_cnt
        FROM {{ source('mrt_20', 'reviews') }}
        WHERE deleted_at IS NULL
        GROUP BY user_id
        UNION ALL
        SELECT
            CAST(r.user_id AS STRING) AS user_id
            , COUNT(DISTINCT r.id) AS review_cnt
        FROM {{ source('reviews', 'reviews') }} AS r
        JOIN {{ source('reviews', 'review_reservation_mappings') }} AS m ON CAST(r.id AS INT) = m.review_id
        WHERE m.reservation_no IS NOT NULL AND r.deleted_at IS NULL
        GROUP BY user_id
        UNION ALL
        SELECT
            CAST(user_id AS STRING) AS user_id
            , COUNT(DISTINCT id) AS review_cnt
        FROM edw.DW_MRT_PRODUCTS_PRODUCT_REVIEWS -- 실제 테이블은 없어짐 ( 24년 이 마지막)
        WHERE deleted_at IS NULL
        GROUP BY user_id
    )
    GROUP BY user_id
)
, SALES AS (
    SELECT
        USER_ID
        , COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER_BUY_CNT
        , COUNT(DISTINCT RESVE_ID) AS TOTAL_BUY_CNT
        , SUM(SALES_KRW_PRICE) AS TOTAL_BUY_PRICE
        , MIN(CASE WHEN RN_ASC=1 THEN CREATE_KST_DT END) AS FIRST_BUY_KST_DT
        , MIN(CASE WHEN RN_ASC=1 THEN RESVE_TYPE END) AS FIRST_BUY_TYPE
        , MIN(CASE WHEN RN_ASC=1 THEN ORDER_ID END) AS FIRST_BUY_ORDER_ID
        , MIN(CASE WHEN RN_ASC=1 THEN RESVE_ID END) AS FIRST_BUY_RESVE_ID
        , MAX(CASE WHEN RN_DESC=1 THEN CREATE_KST_DT END) AS LAST_BUY_KST_DT
        , MAX(CASE WHEN RN_DESC=1 THEN RESVE_TYPE END) AS LAST_BUY_TYPE
        , MAX(CASE WHEN RN_DESC=1 THEN ORDER_ID END) AS LAST_BUY_ORDER_ID
        , MAX(CASE WHEN RN_DESC=1 THEN RESVE_ID END) AS LAST_BUY_RESVE_ID
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN ORDER_ID END) AS RECENT_TRAVEL_ORDER_ID
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN RESVE_ID END) AS RECENT_TRAVEL_RESVE_ID
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN PRODUCT_ID END) AS RECENT_TRAVEL_PRODUCT_ID
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN MRT_TYPE END) AS RECENT_TRAVEL_MRT_TYPE
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN TRAVEL_START_KST_DATE END) AS RECENT_TRAVEL_DEPART_KST_DT
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN TRAVEL_END_KST_DATE END) AS RECENT_TRAVEL_ARRIVE_KST_DT
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN RESVE_PURPOSE_TYPE END) AS RECENT_TRAVEL_RESVE_PURPOSE
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN CITY_NM END) AS RECENT_TRAVEL_CITY
        , MAX(CASE WHEN RECENT_TRAVEL_RN=1 THEN COUNTRY_NM END) AS RECENT_TRAVEL_COUNTRY

        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN ORDER_ID END) AS EXPT_TRAVEL_ORDER_ID
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN RESVE_ID END) AS EXPT_TRAVEL_RESVE_ID
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN PRODUCT_ID END) AS EXPT_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN MRT_TYPE END) AS EXPT_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_TRAVEL_DEPART_KST_DT
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN CITY_NM END) AS EXPT_TRAVEL_CITY
        , MIN(CASE WHEN EXPT_TRAVEL_RN=1 THEN COUNTRY_NM END) AS EXPT_TRAVEL_COUNTRY
        -- FLIGHT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN ORDER_ID END) AS EXPT_FLIGHT_TRAVEL_ORDER_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_ID END) AS EXPT_FLIGHT_TRAVEL_RESVE_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN PRODUCT_ID END) AS EXPT_FLIGHT_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN MRT_TYPE END) AS EXPT_FLIGHT_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_FLIGHT_TRAVEL_DEPART_KST_DATE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_FLIGHT_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_FLIGHT_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN CITY_NM END) AS EXPT_FLIGHT_TRAVEL_CITY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' AND EXPT_TRAVEL_GROUP_RN=1 THEN COUNTRY_NM END) AS EXPT_FLIGHT_TRAVEL_COUNTRY
        -- STAY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN ORDER_ID END) AS EXPT_STAY_TRAVEL_ORDER_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_ID END) AS EXPT_STAY_TRAVEL_RESVE_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN PRODUCT_ID END) AS EXPT_STAY_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN MRT_TYPE END) AS EXPT_STAY_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_STAY_TRAVEL_DEPART_KST_DATE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_STAY_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_STAY_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN CITY_NM END) AS EXPT_STAY_TRAVEL_CITY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'STAY' AND EXPT_TRAVEL_GROUP_RN=1 THEN COUNTRY_NM END) AS EXPT_STAY_TRAVEL_COUNTRY
        -- RIDE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN ORDER_ID END) AS EXPT_RIDE_TRAVEL_ORDER_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_ID END) AS EXPT_RIDE_TRAVEL_RESVE_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN PRODUCT_ID END) AS EXPT_RIDE_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN MRT_TYPE END) AS EXPT_RIDE_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_RIDE_TRAVEL_DEPART_KST_DATE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_RIDE_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_RIDE_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN CITY_NM END) AS EXPT_RIDE_TRAVEL_CITY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'RIDE' AND EXPT_TRAVEL_GROUP_RN=1 THEN COUNTRY_NM END) AS EXPT_RIDE_TRAVEL_COUNTRY
        -- TNA
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN ORDER_ID END) AS EXPT_TNA_TRAVEL_ORDER_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_ID END) AS EXPT_TNA_TRAVEL_RESVE_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN PRODUCT_ID END) AS EXPT_TNA_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN MRT_TYPE END) AS EXPT_TNA_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_TNA_TRAVEL_DEPART_KST_DATE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_TNA_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_TNA_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN CITY_NM END) AS EXPT_TNA_TRAVEL_CITY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'TNA' AND EXPT_TRAVEL_GROUP_RN=1 THEN COUNTRY_NM END) AS EXPT_TNA_TRAVEL_COUNTRY
        -- ETC
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN ORDER_ID END) AS EXPT_ETC_TRAVEL_ORDER_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_ID END) AS EXPT_ETC_TRAVEL_RESVE_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN PRODUCT_ID END) AS EXPT_ETC_TRAVEL_PRODUCT_ID
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN MRT_TYPE END) AS EXPT_ETC_TRAVEL_MRT_TYPE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_START_KST_DATE END) AS EXPT_ETC_TRAVEL_DEPART_KST_DATE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN TRAVEL_END_KST_DATE END) AS EXPT_ETC_TRAVEL_ARRIVE_KST_DT
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN RESVE_PURPOSE_TYPE END) AS EXPT_ETC_TRAVEL_RESVE_PURPOSE
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN CITY_NM END) AS EXPT_ETC_TRAVEL_CITY
        , MIN(CASE WHEN MRT_GROUP_TYPE = 'ETC' AND EXPT_TRAVEL_GROUP_RN=1 THEN COUNTRY_NM END) AS EXPT_ETC_TRAVEL_COUNTRY
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' THEN ORDER_ID END) AS FLIGHT_ORDER_BUY_CNT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' THEN RESVE_ID END) AS FLIGHT_BUY_CNT
        , SUM(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' THEN SALES_KRW_PRICE END) AS FLIGHT_BUY_PRICE
        , MAX(CASE WHEN MRT_GROUP_TYPE = 'FLIGHT' THEN CREATE_KST_DT END) AS LAST_FLIGHT_BUY_KST_DT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'STAY' THEN ORDER_ID END) AS STAY_ORDER_BUY_CNT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'STAY' THEN RESVE_ID END) AS STAY_BUY_CNT
        , SUM(CASE WHEN MRT_GROUP_TYPE = 'STAY' THEN SALES_KRW_PRICE END) AS STAY_BUY_PRICE
        , MAX(CASE WHEN MRT_GROUP_TYPE = 'STAY' THEN CREATE_KST_DT END) AS LAST_STAY_BUY_KST_DT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'RIDE' THEN ORDER_ID END) AS RIDE_ORDER_BUY_CNT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'RIDE' THEN RESVE_ID END) AS RIDE_BUY_CNT
        , SUM(CASE WHEN MRT_GROUP_TYPE = 'RIDE' THEN SALES_KRW_PRICE END) AS RIDE_BUY_PRICE
        , MAX(CASE WHEN MRT_GROUP_TYPE = 'RIDE' THEN CREATE_KST_DT END) AS LAST_RIDE_BUY_KST_DT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'TNA' THEN ORDER_ID END) AS TNA_ORDER_BUY_CNT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'TNA' THEN RESVE_ID END) AS TNA_BUY_CNT
        , SUM(CASE WHEN MRT_GROUP_TYPE = 'TNA' THEN SALES_KRW_PRICE END) AS TNA_BUY_PRICE
        , MAX(CASE WHEN MRT_GROUP_TYPE = 'TNA' THEN CREATE_KST_DT END) AS LAST_TNA_BUY_KST_DT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'ETC' THEN ORDER_ID END) AS ETC_ORDER_BUY_CNT
        , COUNT(DISTINCT CASE WHEN MRT_GROUP_TYPE = 'ETC' THEN RESVE_ID END) AS ETC_BUY_CNT
        , SUM(CASE WHEN MRT_GROUP_TYPE = 'ETC' THEN SALES_KRW_PRICE END) AS ETC_BUY_PRICE
        , MAX(CASE WHEN MRT_GROUP_TYPE = 'ETC' THEN CREATE_KST_DT END) AS LAST_ETC_BUY_KST_DT
    FROM (
        SELECT
            * EXCEPT(RESVE_CNT)
            , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY CREATE_KST_DT ASC) AS RN_ASC
            , ROW_NUMBER() OVER (PARTITION BY USER_ID ORDER BY CREATE_KST_DT DESC) AS RN_DESC
            , CASE WHEN BASIS_TYPE = 'RECENT' THEN ROW_NUMBER() OVER (PARTITION BY USER_ID, BASIS_TYPE ORDER BY TRAVEL_END_KST_DATE DESC, CREATE_KST_DT DESC) END AS RECENT_TRAVEL_RN
            , CASE WHEN BASIS_TYPE = 'EXPT' THEN ROW_NUMBER() OVER (PARTITION BY USER_ID, BASIS_TYPE ORDER BY TRAVEL_START_KST_DATE ASC, CREATE_KST_DT ASC) END AS EXPT_TRAVEL_RN
            , CASE WHEN BASIS_TYPE = 'EXPT' THEN ROW_NUMBER() OVER (PARTITION BY USER_ID, MRT_GROUP_TYPE, BASIS_TYPE ORDER BY TRAVEL_START_KST_DATE ASC, CREATE_KST_DT ASC) END AS EXPT_TRAVEL_GROUP_RN
        FROM (
             SELECT
             USER_ID
            , ORDER_ID
            , RESVE_ID
            , RESVE_TYPE
            , SALES_KRW_PRICE
            , DOMAIN_NM
            , PRODUCT_ID
            , CREATE_KST_DT
            , TRAVEL_START_KST_DATE
            , IFNULL(TRAVEL_END_KST_DATE, TRAVEL_START_KST_DATE) AS TRAVEL_END_KST_DATE
            , CONFIRM_KST_DT
            , RESVE_PURPOSE_TYPE
            , MRT_TYPE
            , CITY_NM
            , COUNTRY_NM
            , CASE
                WHEN MRT_TYPE IN ('flight') THEN 'FLIGHT'
                WHEN MRT_TYPE IN ('hotel', 'pension', 'lodging', 'ticket_lodging') THEN 'STAY'
                WHEN MRT_TYPE IN ('rentalcar', 'ticket_rentalcar') THEN 'RIDE'
                WHEN MRT_TYPE IN ('tour', 'ticket') THEN 'TNA'
                ELSE 'ETC'
            END AS MRT_GROUP_TYPE
            , CASE
                WHEN IFNULL(TRAVEL_END_KST_DATE, TRAVEL_START_KST_DATE) < '{{ var("logical_start_date_kst") }}' THEN 'RECENT'
                WHEN IFNULL(TRAVEL_END_KST_DATE, TRAVEL_START_KST_DATE) >= '{{ var("logical_start_date_kst") }}' THEN 'EXPT'
            END AS BASIS_TYPE
            , MAX(KIND) OVER(PARTITION BY USER_ID, RESVE_ID) AS RESVE_CNT
            FROM {{ ref('MART_SALE_D') }}
            WHERE user_id IS NOT NULL AND user_id NOT IN ('smart_guest', 'guest')
        ) WHERE RESVE_CNT=1 AND CONFIRM_KST_DT IS NOT NULL
    )
    GROUP BY USER_ID
)
SELECT
    DATE('{{ var("logical_start_date_kst") }}') AS BASIS_DT
    , i.user_id AS USER_ID
    , i.JOIN_KST_DT AS JOIN_KST_DT
    , i.JOIN_PLATFORM AS JOIN_PLATFORM
    , IFNULL(i.APP_INSTALL_FLAG, FALSE) AS APP_INSTALL_FLAG
    , i.JOIN_OAUTH_TYPE AS JOIN_OAUTH_TYPE
    , f.login_platform AS LAST_LOGIN_PLATFORM
    , f.login_kst_dt AS LAST_LOGIN_KST_DT
    , i.DORMANT_FLAG AS DORMANT_FLAG
    , i.DORMANT_KST_DT AS DORMANT_KST_DT
    , i.LEAVE_FLAG AS LEAVE_FLAG
    , i.LEAVE_KST_DT AS LEAVE_KST_DT
    , IFNULL(i.SMS_RECV_AGREE, FALSE) AS SMS_RECV_AGREE
    , IFNULL(i.PUSH_RECV_AGREE, FALSE) AS PUSH_RECV_AGREE
    , IFNULL(i.MAIL_RECV_AGREE, FALSE) AS MAIL_RECV_AGREE
    , IFNULL(i.POSITION_ARGREEMENT_FLAG, FALSE) AS POSITION_ARGREEMENT_FLAG
    , IFNULL(i.PHONE_VALID_FLAG, FALSE) AS PHONE_VALID_FLAG
    , a.REP_AGE AS REP_AGE
    , a.REP_SEX AS USER_GENDER_NM
    , a.AGES AS COMPANION_AGE_GENDER_GROUP
    , i.GUIDE_FLAG AS GUIDE_FLAG
    , i.MRT_STAFF_FLAG AS MRT_STAFF_FLAG
    , i.TEST_FLAG AS TEST_FLAG
    , inf.invite_cnt AS INVITE_FRND_CNT
    , r.review_cnt AS REVIEW_CNT
    , c.remain_coupon_cnt AS OWN_COUPON_CNT
    , c.remain_coupon_ids AS OWN_COUPON_NO
    , IFNULL(s.TOTAL_ORDER_BUY_CNT, 0) AS TOTAL_ORDER_BUY_CNT
    , IFNULL(s.TOTAL_BUY_CNT, 0) AS TOTAL_BUY_CNT
    , ROUND(s.TOTAL_BUY_PRICE, 2) AS TOTAL_BUY_PRICE
    , s.FIRST_BUY_KST_DT
    , s.FIRST_BUY_TYPE
    , s.FIRST_BUY_ORDER_ID
    , s.FIRST_BUY_RESVE_ID
    , s.LAST_BUY_KST_DT
    , s.LAST_BUY_TYPE
    , s.LAST_BUY_ORDER_ID
    , s.LAST_BUY_RESVE_ID
    , s.RECENT_TRAVEL_ORDER_ID
    , s.RECENT_TRAVEL_RESVE_ID
    , s.RECENT_TRAVEL_PRODUCT_ID
    , s.RECENT_TRAVEL_MRT_TYPE
    , s.RECENT_TRAVEL_DEPART_KST_DT
    , s.RECENT_TRAVEL_ARRIVE_KST_DT
    , s.RECENT_TRAVEL_RESVE_PURPOSE
    , s.RECENT_TRAVEL_CITY
    , s.RECENT_TRAVEL_COUNTRY
    , s.EXPT_TRAVEL_ORDER_ID
    , s.EXPT_TRAVEL_RESVE_ID
    , s.EXPT_TRAVEL_PRODUCT_ID
    , s.EXPT_TRAVEL_MRT_TYPE
    , s.EXPT_TRAVEL_DEPART_KST_DT
    , s.EXPT_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_TRAVEL_RESVE_PURPOSE
    , s.EXPT_TRAVEL_CITY
    , s.EXPT_TRAVEL_COUNTRY
    , s.EXPT_FLIGHT_TRAVEL_ORDER_ID
    , s.EXPT_FLIGHT_TRAVEL_RESVE_ID
    , s.EXPT_FLIGHT_TRAVEL_PRODUCT_ID
    , s.EXPT_FLIGHT_TRAVEL_MRT_TYPE
    , s.EXPT_FLIGHT_TRAVEL_DEPART_KST_DATE
    , s.EXPT_FLIGHT_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_FLIGHT_TRAVEL_RESVE_PURPOSE
    , s.EXPT_FLIGHT_TRAVEL_CITY
    , s.EXPT_FLIGHT_TRAVEL_COUNTRY
    , s.EXPT_STAY_TRAVEL_ORDER_ID
    , s.EXPT_STAY_TRAVEL_RESVE_ID
    , s.EXPT_STAY_TRAVEL_PRODUCT_ID
    , s.EXPT_STAY_TRAVEL_MRT_TYPE
    , s.EXPT_STAY_TRAVEL_DEPART_KST_DATE
    , s.EXPT_STAY_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_STAY_TRAVEL_RESVE_PURPOSE
    , s.EXPT_STAY_TRAVEL_CITY
    , s.EXPT_STAY_TRAVEL_COUNTRY
    , s.EXPT_RIDE_TRAVEL_ORDER_ID
    , s.EXPT_RIDE_TRAVEL_RESVE_ID
    , s.EXPT_RIDE_TRAVEL_PRODUCT_ID
    , s.EXPT_RIDE_TRAVEL_MRT_TYPE
    , s.EXPT_RIDE_TRAVEL_DEPART_KST_DATE
    , s.EXPT_RIDE_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_RIDE_TRAVEL_RESVE_PURPOSE
    , s.EXPT_RIDE_TRAVEL_CITY
    , s.EXPT_RIDE_TRAVEL_COUNTRY
    , s.EXPT_TNA_TRAVEL_ORDER_ID
    , s.EXPT_TNA_TRAVEL_RESVE_ID
    , s.EXPT_TNA_TRAVEL_PRODUCT_ID
    , s.EXPT_TNA_TRAVEL_MRT_TYPE
    , s.EXPT_TNA_TRAVEL_DEPART_KST_DATE
    , s.EXPT_TNA_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_TNA_TRAVEL_RESVE_PURPOSE
    , s.EXPT_TNA_TRAVEL_CITY
    , s.EXPT_TNA_TRAVEL_COUNTRY
    , s.EXPT_ETC_TRAVEL_ORDER_ID
    , s.EXPT_ETC_TRAVEL_RESVE_ID
    , s.EXPT_ETC_TRAVEL_PRODUCT_ID
    , s.EXPT_ETC_TRAVEL_MRT_TYPE
    , s.EXPT_ETC_TRAVEL_DEPART_KST_DATE
    , s.EXPT_ETC_TRAVEL_ARRIVE_KST_DT
    , s.EXPT_ETC_TRAVEL_RESVE_PURPOSE
    , s.EXPT_ETC_TRAVEL_CITY
    , s.EXPT_ETC_TRAVEL_COUNTRY
    , s.FLIGHT_ORDER_BUY_CNT
    , s.FLIGHT_BUY_CNT
    , IFNULL(ROUND(s.FLIGHT_BUY_PRICE), 0) AS FLIGHT_BUY_PRICE
    , s.LAST_FLIGHT_BUY_KST_DT AS LAST_FLIGHT_BUY_KST_DT
    , s.STAY_ORDER_BUY_CNT
    , s.STAY_BUY_CNT
    , IFNULL(ROUND(s.STAY_BUY_PRICE), 0) AS STAY_BUY_PRICE
    , s.LAST_STAY_BUY_KST_DT AS LAST_STAY_BUY_KST_DT
    , s.RIDE_ORDER_BUY_CNT
    , s.RIDE_BUY_CNT
    , IFNULL(ROUND(s.RIDE_BUY_PRICE), 0) AS RIDE_BUY_PRICE
    , s.LAST_RIDE_BUY_KST_DT AS LAST_RIDE_BUY_KST_DT
    , s.TNA_ORDER_BUY_CNT
    , s.TNA_BUY_CNT
    , IFNULL(ROUND(s.TNA_BUY_PRICE), 0) AS TNA_BUY_PRICE
    , s.LAST_TNA_BUY_KST_DT AS LAST_TNA_BUY_KST_DT
    , s.ETC_ORDER_BUY_CNT
    , s.ETC_BUY_CNT
    , IFNULL(ROUND(s.ETC_BUY_PRICE), 0) AS ETC_BUY_PRICE
    , s.LAST_ETC_BUY_KST_DT AS LAST_ETC_BUY_KST_DT
    , i.UPDATE_KST_DT
    , DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM {{ ref('DIM_USER_INFO') }} i
LEFT JOIN FACT f ON f.user_id = i.user_id
LEFT JOIN AIR_USER_INFO a ON f.user_id = a.user_id
LEFT JOIN COUPON c ON f.user_id = c.user_id
LEFT JOIN (
    SELECT
        CAST(user_id AS STRING) AS user_id
        , COUNT(DISTINCT invited_user_id) AS invite_cnt
    FROM {{ source('mrt_20', 'invite_friends') }}
    GROUP BY user_id
) inf ON f.user_id = inf.user_id
LEFT JOIN REVIEWS r ON f.user_id = r.user_id
LEFT JOIN SALES s ON f.user_id = s.user_id