{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_AIR_ANCILLARY_SALE_D'
    )
}}

WITH ANCILLARY_SALE AS (
SELECT CAST(S.REG_DTM AS DATE) AS BASIS_DATE
    ,  CAST(S.PNR_SEQNO AS FLOAT64) AS PNR_NO
    ,  CONCAT('f', S.PNR_SEQNO) AS RESVE_ID
    ,  CONCAT(S.PAY_DET_SN) AS RESVE_OPTION_ID
    ,  LOWER(S.STATUS) AS RECENT_STATUS
    ,  CAST(S.USR_ID AS STRING) AS USER_ID
    ,  S.DEP_STN_CD AS DEPART_AIRPORT_CD
    ,  S.DEP_DTM AS DEPART_KST_DT
    ,  S.ARR_STN_CD AS ARRIVE_AIRPORT_CD
    ,  PARSE_TIMESTAMP('%Y%m%d%H%M%S', S.ARR_DTM) AS ARRIVE_KST_DT
    ,  A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
    ,  A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
    ,  A.SALE_FORM_CD AS SALE_FORM_CD
    ,  A.SALE_AGG_TYPE AS SALE_AGG_TYPE
    ,  A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
    ,  LOWER(S.ANC_TYPE) AS ANCILLARY_TYPE
    ,  S.ANC_NM AS ANCILLARY_NM
    ,  S.ANC_DESC AS ANCILLARY_DESC
    ,  CAST(S.CHARGE AS FLOAT64) AS SALES_PRICE
    ,  S.CURRENCY AS SALES_PRICE_CUR_TYPE
    ,  ROUND(CAST(S.CHARGE AS FLOAT64) * COALESCE(IFNULL(CASE WHEN ce.to_currency in ('JPY','VND') THEN SAFE_DIVIDE(ce.standard_exchange_rate, 100) ELSE ce.standard_exchange_rate END
                                     , mc.krw_rate), 1), 3) AS SALES_KRW_PRICE
    ,  S.REG_DTM AS CREATED_KST_DT
    ,  IFNULL(S.UPD_DTM, S.REG_DTM) AS UPDATED_KST_DT
    ,  S.CNT AS RESVE_CNT
FROM {{ source('air', 'TB_AIR_MRT_ANCILLARY_GATEWAY_SALES') }} S
LEFT JOIN {{ ref('MART_AIR_PNR_SALE_D') }} A ON S.PNR_SEQNO = A.PNR_NO AND A.KIND = 1
LEFT JOIN {{ source('settles', 'currency_exchanges') }} ce ON CASE WHEN S.ANC_TYPE = 'DUTY_FREE' THEN CASE WHEN  CAST(S.DEP_DTM AS DATE) <= '{{ var("logical_start_date_kst") }}' THEN CAST(S.DEP_DTM AS DATE)
                                                           ELSE '{{ var("logical_start_date_kst") }}' END
                                                      ELSE CAST(S.REG_DTM AS DATE) END = ce.standard_date AND ce.to_currency = S.CURRENCY AND ce.deleted_at IS NULL
LEFT JOIN {{ ref('mart_currency') }} mc ON CASE WHEN S.ANC_TYPE = 'DUTY_FREE' THEN CASE WHEN  CAST(S.DEP_DTM AS DATE) <= '{{ var("logical_start_date_kst") }}' THEN CAST(S.DEP_DTM AS DATE)
                                            ELSE '{{ var("logical_start_date_kst") }}' END
                                       ELSE CAST(S.REG_DTM AS DATE) END = CAST(mc.day AS DATE) AND mc.code = S.CURRENCY
LEFT JOIN {{ ref('DIM_USER_INFO') }} U ON CAST(S.USR_ID AS STRING) = U.USER_ID
WHERE (U.TEST_FLAG <> true OR U.USER_ID IS NULL)
),
PENALTY_INSURANCE_SALE AS (
    SELECT CAST(IR110.REG_DTM AS DATE) AS BASIS_DATE
         ,  CAST(IR110.PNR_SEQNO AS FLOAT64) AS PNR_NO
         ,  CONCAT('f', CAST(IR110.PNR_SEQNO AS STRING)) AS RESVE_ID
         ,  IR110.VIRTUAL_CONTRACT_NO AS RESVE_OPTION_ID
         ,  CASE WHEN IR110.SBSCRB_STATUS IN ('ISKK', 'ISCX','ISTK','ISTX') THEN 'paid'
                 ELSE 'cancelled' END AS RECENT_STATUS
         ,  A.USER_ID AS USER_ID
         ,  S.DEP_AIRPORT_CD AS DEPART_AIRPORT_CD
         ,  A.DEPART_KST_DT AS DEPART_KST_DT
         ,  A.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
         ,  A.RETURN_KST_DT AS ARRIVE_KST_DT
         ,  A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
         ,  A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
         ,  A.SALE_FORM_CD AS SALE_FORM_CD
         ,  A.SALE_AGG_TYPE AS SALE_AGG_TYPE
         ,  A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
         ,  'cancel_insurance' AS ANCILLARY_TYPE
         ,  '취소 위약금 보험' AS ANCILLARY_NM
         ,  CAST(NULL AS STRING) AS ANCILLARY_DESC
         ,  IR110.ind_insu_amt AS SALES_PRICE
         ,  'KRW' AS SALES_PRICE_CUR_TYPE
         ,  IR110.ind_insu_amt AS SALES_KRW_PRICE
         ,  IR110.INSU_CHG_DATE AS CANCEL_KST_DATE
         ,  IR110.INSU_RTN_AMT AS CANCEL_SALES_KRW_PRICE
         ,  IR110.REG_DTM AS CREATED_KST_DT
         ,  IFNULL(IR110.UPD_DTM, IR110.REG_DTM) AS UPDATED_KST_DT
    FROM {{ source('air_stream', 'flight_oracle_MRT_TB_INS_RV110') }} IR110
    LEFT JOIN {{ source('air_stream', 'flight_oracle_MRT_TB_INS_RV100') }} IR100 ON IR110.PNR_SEQNO = IR100.PNR_SEQNO
    LEFT JOIN {{ ref('MART_AIR_PNR_SALE_D') }} A ON IR100.PNR_SEQNO = A.PNR_NO AND A.KIND = 1
    LEFT JOIN {{ source('air', 'TB_AIR_RV120') }} S ON A.PNR_NO = S.PNR_SEQNO AND S.ITIN_NO = 1.0
-- ISKK : 계약완료 / ISCX : 해지실패 / ISTK : 가배서 완료 / ISTX : 가배서 실패 / ISCK : 해지
    WHERE IR110.SBSCRB_STATUS IN ('ISKK', 'ISCX','ISTK','ISTX','ISCK')
      AND IR110.VIRTUAL_CONTRACT_NO IS NOT NULL
      AND A.PNR_NO IS NOT NULL -- 모수 제외 : 테스트 유저 등
),
SALES AS (
    SELECT A.BASIS_DATE AS BASIS_DATE
        ,  A.PNR_NO AS PNR_NO
        ,  A.RESVE_ID AS RESVE_ID
        ,  A.RESVE_OPTION_ID AS RESVE_OPTION_ID
        ,  A.RECENT_STATUS AS RECENT_STATUS
        ,  'ANCILLARY' AS DOMAIN_NM
        ,  A.USER_ID AS USER_ID
        ,  A.DEPART_AIRPORT_CD AS DEPART_AIRPORT_CD
        ,  A.DEPART_KST_DT AS DEPART_KST_DT
        ,  A.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
        ,  A.ARRIVE_KST_DT AS ARRIVE_KST_DT
        ,  A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
        ,  A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
        ,  A.SALE_FORM_CD AS SALE_FORM_CD
        ,  A.SALE_AGG_TYPE AS SALE_AGG_TYPE
        ,  A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
        ,  A.ANCILLARY_TYPE AS ANCILLARY_TYPE
        ,  A.ANCILLARY_NM AS ANCILLARY_NM
        ,  A.ANCILLARY_DESC AS ANCILLARY_DESC
        ,  A.SALES_PRICE AS SALES_PRICE
        ,  A.SALES_PRICE_CUR_TYPE AS SALES_PRICE_CUR_TYPE
        ,  A.SALES_KRW_PRICE AS SALES_KRW_PRICE
        ,  A.CREATED_KST_DT AS CREATED_KST_DT
        ,  A.UPDATED_KST_DT AS UPDATED_KST_DT
        ,  CAST(NULL AS DATE) AS CANCEL_KST_DATE
        , CAST(NULL AS FLOAT64) AS CANCEL_SALES_KRW_PRICE
        ,  A.RESVE_CNT AS RESVE_CNT
    FROM ANCILLARY_SALE A

    UNION ALL

    SELECT B.BASIS_DATE AS BASIS_DATE
         , B.PNR_NO AS PNR_NO
         , B.RESVE_ID AS RESVE_ID
         , B.RESVE_OPTION_ID AS RESVE_OPTION_ID
         , B.RECENT_STATUS AS RECENT_STATUS
         , 'PENALTY INSURANCE' AS DOMAIN_NM
         , B.USER_ID AS USER_ID
         , B.DEPART_AIRPORT_CD AS DEPART_AIRPORT_CD
         , B.DEPART_KST_DT AS DEPART_KST_DT
         , B.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
         , B.ARRIVE_KST_DT AS ARRIVE_KST_DT
         , B.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
         , B.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
         , B.SALE_FORM_CD AS SALE_FORM_CD
         , B.SALE_AGG_TYPE AS SALE_AGG_TYPE
         , B.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
         , B.ANCILLARY_TYPE AS ANCILLARY_TYPE
         , B.ANCILLARY_NM AS ANCILLARY_NM
         , B.ANCILLARY_DESC AS ANCILLARY_DESC
         , B.SALES_PRICE AS SALES_PRICE
         , B.SALES_PRICE_CUR_TYPE AS SALES_PRICE_CUR_TYPE
         , B.SALES_KRW_PRICE AS SALES_KRW_PRICE
         , B.CREATED_KST_DT AS CREATED_KST_DT
         , B.UPDATED_KST_DT AS UPDATED_KST_DT
         , B.CANCEL_KST_DATE AS CANCEL_KST_DATE
         , B.CANCEL_SALES_KRW_PRICE AS CANCEL_SALES_KRW_PRICE
         , 1 AS RESVE_CNT
    FROM PENALTY_INSURANCE_SALE B
),
RESULT AS (
SELECT A.BASIS_DATE
     , A.PNR_NO
     , A.RESVE_ID
     , CONCAT('a', CAST(A.PNR_NO AS STRING), '-', CAST(ROW_NUMBER() OVER (PARTITION BY CAST(A.PNR_NO AS STRING) ORDER BY A.BASIS_DATE) AS STRING)) AS RESVE_UNIQUE_ID
     , A.RESVE_OPTION_ID
     , A.RECENT_STATUS
     , A.DOMAIN_NM
     , A.USER_ID
     , A.DEPART_AIRPORT_CD
     , A.DEPART_KST_DT
     , A.ARRIVE_AIRPORT_CD
     , A.ARRIVE_KST_DT
     , A.STOCK_AIRLINE_CD
     , A.ON_OFF_RESVE_FLAG
     , A.SALE_FORM_CD
     , A.SALE_AGG_TYPE
     , A.DOMESTIC_INTERNATIONAL_DIV_CD
     , A.ANCILLARY_TYPE
     , A.ANCILLARY_NM
     , A.ANCILLARY_DESC
     , A.SALES_PRICE
     , A.SALES_PRICE_CUR_TYPE
     , A.SALES_KRW_PRICE
     , A.CREATED_KST_DT
     , A.UPDATED_KST_DT
     , A.CANCEL_KST_DATE
     , A.CANCEL_SALES_KRW_PRICE
     , A.RESVE_CNT
FROM SALES A
),
CANCEL AS (
SELECT IFNULL(A.CANCEL_KST_DATE, CAST(A.UPDATED_KST_DT AS DATE)) AS BASIS_DATE
    ,  A.PNR_NO AS PNR_NO
    ,  A.RESVE_ID AS RESVE_ID
    ,  A.RESVE_OPTION_ID AS RESVE_OPTION_ID
    ,  A.RESVE_UNIQUE_ID AS RESVE_UNIQUE_ID
    ,  A.RECENT_STATUS AS RECENT_STATUS
    ,  A.DOMAIN_NM AS DOMAIN_NM
    ,  A.USER_ID AS USER_ID
    ,  A.DEPART_AIRPORT_CD AS DEPART_AIRPORT_CD
    ,  A.DEPART_KST_DT AS DEPART_KST_DT
    ,  A.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
    ,  A.ARRIVE_KST_DT AS ARRIVE_KST_DT
    ,  A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
    ,  A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
    ,  A.SALE_FORM_CD AS SALE_FORM_CD
    ,  A.SALE_AGG_TYPE AS SALE_AGG_TYPE
    ,  A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
    ,  A.ANCILLARY_TYPE AS ANCILLARY_TYPE
    ,  A.ANCILLARY_NM AS ANCILLARY_NM
    ,  A.ANCILLARY_DESC AS ANCILLARY_DESC
    ,  IFNULL(A.CANCEL_SALES_KRW_PRICE, A.SALES_PRICE) * -1 AS SALES_PRICE
    ,  IFNULL(A.SALES_PRICE_CUR_TYPE, 'KRW') AS SALES_PRICE_CUR_TYPE
    ,  IFNULL(A.CANCEL_SALES_KRW_PRICE, A.SALES_KRW_PRICE) * -1 AS SALES_KRW_PRICE
    ,  A.CREATED_KST_DT AS CREATED_KST_DT
    ,  A.UPDATED_KST_DT AS UPDATED_KST_DT
    ,  IFNULL(A.CANCEL_KST_DATE, CAST(A.UPDATED_KST_DT AS DATE)) AS CANCEL_KST_DATE
    ,  A.RESVE_CNT AS RESVE_CNT
      FROM RESULT A
     WHERE A.RECENT_STATUS = 'cancelled'
)
SELECT A.BASIS_DATE AS BASIS_DATE
    ,  A.PNR_NO AS PNR_NO
    ,  A.RESVE_ID AS RESVE_ID
    ,  A.RESVE_OPTION_ID AS RESVE_OPTION_ID
    ,  A.RESVE_UNIQUE_ID AS RESVE_UNIQUE_ID
    ,  A.RECENT_STATUS AS RECENT_STATUS
    ,  A.DOMAIN_NM AS DOMAIN_NM
    ,  1 AS KIND
    ,  A.USER_ID AS USER_ID
    ,  A.DEPART_AIRPORT_CD AS DEPART_AIRPORT_CD
    ,  A.DEPART_KST_DT AS DEPART_KST_DT
    ,  A.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
    ,  A.ARRIVE_KST_DT AS ARRIVE_KST_DT
    ,  A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
    ,  A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
    ,  A.SALE_FORM_CD AS SALE_FORM_CD
    ,  A.SALE_AGG_TYPE AS SALE_AGG_TYPE
    ,  A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
    ,  A.ANCILLARY_TYPE AS ANCILLARY_TYPE
    ,  A.ANCILLARY_NM AS ANCILLARY_NM
    ,  A.ANCILLARY_DESC AS ANCILLARY_DESC
    ,  A.SALES_PRICE AS SALES_PRICE
    ,  A.SALES_PRICE_CUR_TYPE AS SALES_PRICE_CUR_TYPE
    ,  A.SALES_KRW_PRICE AS SALES_KRW_PRICE
    ,  A.CREATED_KST_DT AS CREATED_KST_DT
    ,  A.UPDATED_KST_DT AS UPDATED_KST_DT
    ,  A.CANCEL_KST_DATE AS CANCEL_KST_DATE
    ,  A.RESVE_CNT AS RESVE_CNT
    ,  DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM RESULT A

UNION ALL

SELECT A.BASIS_DATE AS BASIS_DATE
     , A.PNR_NO AS PNR_NO
     , A.RESVE_ID AS RESVE_ID
     , A.RESVE_OPTION_ID AS RESVE_OPTION_ID
     , A.RESVE_UNIQUE_ID AS RESVE_UNIQUE_ID
     , A.RECENT_STATUS AS RECENT_STATUS
     , A.DOMAIN_NM AS DOMAIN_NM
     , 2 AS KIND
     , A.USER_ID AS USER_ID
     , A.DEPART_AIRPORT_CD AS DEPART_AIRPORT_CD
     , A.DEPART_KST_DT AS DEPART_KST_DT
     , A.ARRIVE_AIRPORT_CD AS ARRIVE_AIRPORT_CD
     , A.ARRIVE_KST_DT AS ARRIVE_KST_DT
     , A.STOCK_AIRLINE_CD AS STOCK_AIRLINE_CD
     , A.ON_OFF_RESVE_FLAG AS ON_OFF_RESVE_FLAG
     , A.SALE_FORM_CD AS SALE_FORM_CD
     , A.SALE_AGG_TYPE AS SALE_AGG_TYPE
     , A.DOMESTIC_INTERNATIONAL_DIV_CD AS DOMESTIC_INTERNATIONAL_DIV_CD
     , A.ANCILLARY_TYPE AS ANCILLARY_TYPE
     , A.ANCILLARY_NM AS ANCILLARY_NM
     , A.ANCILLARY_DESC AS ANCILLARY_DESC
     , A.SALES_PRICE AS SALES_PRICE
     , A.SALES_PRICE_CUR_TYPE AS SALES_PRICE_CUR_TYPE
     , A.SALES_KRW_PRICE AS SALES_KRW_PRICE
     , A.CREATED_KST_DT AS CREATED_KST_DT
     , A.UPDATED_KST_DT AS UPDATED_KST_DT
     , A.CANCEL_KST_DATE AS CANCEL_KST_DATE
     , A.RESVE_CNT AS RESVE_CNT
     , DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM CANCEL A