{{
    config(
        materialized='table',
        schema='mrt_mart',
        alias='mart_currency'
    )
}}

WITH DAY_BASE AS (
    SELECT day
    FROM UNNEST(GENERATE_timestamp_ARRAY(TIMESTAMP('2014-06-23'), TIMESTAMP(DATE_SUB(DATE(CURRENT_TIMESTAMP(), "Asia/Seoul"), INTERVAL 1 DAY)), INTERVAL 1 DAY)) AS day
),
     CURRENCY_RANKED AS (
         SELECT
             day, id,
             valid_at_kst AS valid_at,
             created_at_kst AS created_at,
             updated_at_kst AS updated_at,
             base_currency_code,
             rates,
             ROW_NUMBER() OVER (PARTITION BY day ORDER BY valid_at) AS row_num
         FROM DAY_BASE AS d
                  LEFT JOIN {{ source('mrt_20', 'currencies') }} AS c ON DATE(c.valid_at_kst) = DATE(day)
     ),
     BEFORE_FILL AS (
         SELECT *, LAG(id) OVER (ORDER BY day) AS before_id
         FROM CURRENCY_RANKED
         WHERE row_num = 1
     ),
     FIRST_RESULT AS (
         SELECT
             b.day,
             IFNULL(b.id, t.id) AS id,
             IFNULL(b.valid_at, t.valid_at) AS valid_at,
             IFNULL(b.created_at, t.created_at) AS created_at,
             IFNULL(b.updated_at, t.updated_at) AS updated_at,
             IFNULL(b.base_currency_code, t.base_currency_code) AS base_currency_code,
             IFNULL(b.rates, t.rates) AS rates
         FROM BEFORE_FILL AS b
                  LEFT JOIN CURRENCY_RANKED t ON t.id = b.before_id AND b.id IS NULL
     ),
     CURRENCY_ARRAY AS (
         SELECT day, valid_at, base_currency_code,
                [
                    struct('SHP' AS code, JSON_EXTRACT_SCALAR(rates, '$.SHP') AS rate),
                    struct('IQD' AS code, JSON_EXTRACT_SCALAR(rates, '$.IQD') AS rate),
                    struct('TND' AS code, JSON_EXTRACT_SCALAR(rates, '$.TND') AS rate),
                    struct('BYN' AS code, JSON_EXTRACT_SCALAR(rates, '$.BYN') AS rate),
                    struct('EGP' AS code, JSON_EXTRACT_SCALAR(rates, '$.EGP') AS rate),
                    struct('CHF' AS code, JSON_EXTRACT_SCALAR(rates, '$.CHF') AS rate),
                    struct('RUB' AS code, JSON_EXTRACT_SCALAR(rates, '$.RUB') AS rate),
                    struct('KHR' AS code, JSON_EXTRACT_SCALAR(rates, '$.KHR') AS rate),
                    struct('ILS' AS code, JSON_EXTRACT_SCALAR(rates, '$.ILS') AS rate),
                    struct('SAR' AS code, JSON_EXTRACT_SCALAR(rates, '$.SAR') AS rate),
                    struct('PEN' AS code, JSON_EXTRACT_SCALAR(rates, '$.PEN') AS rate),
                    struct('INR' AS code, JSON_EXTRACT_SCALAR(rates, '$.INR') AS rate),
                    struct('JOD' AS code, JSON_EXTRACT_SCALAR(rates, '$.JOD') AS rate),
                    struct('JEP' AS code, JSON_EXTRACT_SCALAR(rates, '$.JEP') AS rate),
                    struct('MAD' AS code, JSON_EXTRACT_SCALAR(rates, '$.MAD') AS rate),
                    struct('LBP' AS code, JSON_EXTRACT_SCALAR(rates, '$.LBP') AS rate),
                    struct('MKD' AS code, JSON_EXTRACT_SCALAR(rates, '$.MKD') AS rate),
                    struct('BTC' AS code, JSON_EXTRACT_SCALAR(rates, '$.BTC') AS rate),
                    struct('HUF' AS code, JSON_EXTRACT_SCALAR(rates, '$.HUF') AS rate),
                    struct('KPW' AS code, JSON_EXTRACT_SCALAR(rates, '$.KPW') AS rate),
                    struct('TZS' AS code, JSON_EXTRACT_SCALAR(rates, '$.TZS') AS rate),
                    struct('XPT' AS code, JSON_EXTRACT_SCALAR(rates, '$.XPT') AS rate),
                    struct('SVC' AS code, JSON_EXTRACT_SCALAR(rates, '$.SVC') AS rate),
                    struct('HTG' AS code, JSON_EXTRACT_SCALAR(rates, '$.HTG') AS rate),
                    struct('TOP' AS code, JSON_EXTRACT_SCALAR(rates, '$.TOP') AS rate),
                    struct('STD' AS code, JSON_EXTRACT_SCALAR(rates, '$.STD') AS rate),
                    struct('PAB' AS code, JSON_EXTRACT_SCALAR(rates, '$.PAB') AS rate),
                    struct('SGD' AS code, JSON_EXTRACT_SCALAR(rates, '$.SGD') AS rate),
                    struct('GNF' AS code, JSON_EXTRACT_SCALAR(rates, '$.GNF') AS rate),
                    struct('LRD' AS code, JSON_EXTRACT_SCALAR(rates, '$.LRD') AS rate),
                    struct('JPY' AS code, JSON_EXTRACT_SCALAR(rates, '$.JPY') AS rate),
                    struct('AUD' AS code, JSON_EXTRACT_SCALAR(rates, '$.AUD') AS rate),
                    struct('GMD' AS code, JSON_EXTRACT_SCALAR(rates, '$.GMD') AS rate),
                    struct('MNT' AS code, JSON_EXTRACT_SCALAR(rates, '$.MNT') AS rate),
                    struct('FJD' AS code, JSON_EXTRACT_SCALAR(rates, '$.FJD') AS rate),
                    struct('GIP' AS code, JSON_EXTRACT_SCALAR(rates, '$.GIP') AS rate),
                    struct('MRU' AS code, JSON_EXTRACT_SCALAR(rates, '$.MRU') AS rate),
                    struct('CDF' AS code, JSON_EXTRACT_SCALAR(rates, '$.CDF') AS rate),
                    struct('BSD' AS code, JSON_EXTRACT_SCALAR(rates, '$.BSD') AS rate),
                    struct('SBD' AS code, JSON_EXTRACT_SCALAR(rates, '$.SBD') AS rate),
                    struct('LTL' AS code, JSON_EXTRACT_SCALAR(rates, '$.LTL') AS rate),
                    struct('TRY' AS code, JSON_EXTRACT_SCALAR(rates, '$.TRY') AS rate),
                    struct('XAU' AS code, JSON_EXTRACT_SCALAR(rates, '$.XAU') AS rate),
                    struct('SSP' AS code, JSON_EXTRACT_SCALAR(rates, '$.SSP') AS rate),
                    struct('EEK' AS code, JSON_EXTRACT_SCALAR(rates, '$.EEK') AS rate),
                    struct('RON' AS code, JSON_EXTRACT_SCALAR(rates, '$.RON') AS rate),
                    struct('ZMK' AS code, JSON_EXTRACT_SCALAR(rates, '$.ZMK') AS rate),
                    struct('FKP' AS code, JSON_EXTRACT_SCALAR(rates, '$.FKP') AS rate),
                    struct('HNL' AS code, JSON_EXTRACT_SCALAR(rates, '$.HNL') AS rate),
                    struct('QAR' AS code, JSON_EXTRACT_SCALAR(rates, '$.QAR') AS rate),
                    struct('BZD' AS code, JSON_EXTRACT_SCALAR(rates, '$.BZD') AS rate),
                    struct('GHS' AS code, JSON_EXTRACT_SCALAR(rates, '$.GHS') AS rate),
                    struct('MOP' AS code, JSON_EXTRACT_SCALAR(rates, '$.MOP') AS rate),
                    struct('MXN' AS code, JSON_EXTRACT_SCALAR(rates, '$.MXN') AS rate),
                    struct('VES' AS code, JSON_EXTRACT_SCALAR(rates, '$.VES') AS rate),
                    struct('PYG' AS code, JSON_EXTRACT_SCALAR(rates, '$.PYG') AS rate),
                    struct('HRK' AS code, JSON_EXTRACT_SCALAR(rates, '$.HRK') AS rate),
                    struct('BOB' AS code, JSON_EXTRACT_SCALAR(rates, '$.BOB') AS rate),
                    struct('MMK' AS code, JSON_EXTRACT_SCALAR(rates, '$.MMK') AS rate),
                    struct('AOA' AS code, JSON_EXTRACT_SCALAR(rates, '$.AOA') AS rate),
                    struct('CAD' AS code, JSON_EXTRACT_SCALAR(rates, '$.CAD') AS rate),
                    struct('MUR' AS code, JSON_EXTRACT_SCALAR(rates, '$.MUR') AS rate),
                    struct('SEK' AS code, JSON_EXTRACT_SCALAR(rates, '$.SEK') AS rate),
                    struct('JMD' AS code, JSON_EXTRACT_SCALAR(rates, '$.JMD') AS rate),
                    struct('LVL' AS code, JSON_EXTRACT_SCALAR(rates, '$.LVL') AS rate),
                    struct('BDT' AS code, JSON_EXTRACT_SCALAR(rates, '$.BDT') AS rate),
                    struct('VND' AS code, JSON_EXTRACT_SCALAR(rates, '$.VND') AS rate),
                    struct('RWF' AS code, JSON_EXTRACT_SCALAR(rates, '$.RWF') AS rate),
                    struct('CUP' AS code, JSON_EXTRACT_SCALAR(rates, '$.CUP') AS rate),
                    struct('PKR' AS code, JSON_EXTRACT_SCALAR(rates, '$.PKR') AS rate),
                    struct('KZT' AS code, JSON_EXTRACT_SCALAR(rates, '$.KZT') AS rate),
                    struct('SLL' AS code, JSON_EXTRACT_SCALAR(rates, '$.SLL') AS rate),
                    struct('ISK' AS code, JSON_EXTRACT_SCALAR(rates, '$.ISK') AS rate),
                    struct('MVR' AS code, JSON_EXTRACT_SCALAR(rates, '$.MVR') AS rate),
                    struct('XPF' AS code, JSON_EXTRACT_SCALAR(rates, '$.XPF') AS rate),
                    struct('SZL' AS code, JSON_EXTRACT_SCALAR(rates, '$.SZL') AS rate),
                    struct('THB' AS code, JSON_EXTRACT_SCALAR(rates, '$.THB') AS rate),
                    struct('BWP' AS code, JSON_EXTRACT_SCALAR(rates, '$.BWP') AS rate),
                    struct('NPR' AS code, JSON_EXTRACT_SCALAR(rates, '$.NPR') AS rate),
                    struct('SYP' AS code, JSON_EXTRACT_SCALAR(rates, '$.SYP') AS rate),
                    struct('LSL' AS code, JSON_EXTRACT_SCALAR(rates, '$.LSL') AS rate),
                    struct('HKD' AS code, JSON_EXTRACT_SCALAR(rates, '$.HKD') AS rate),
                    struct('MRO' AS code, JSON_EXTRACT_SCALAR(rates, '$.MRO') AS rate),
                    struct('CLP' AS code, JSON_EXTRACT_SCALAR(rates, '$.CLP') AS rate),
                    struct('DJF' AS code, JSON_EXTRACT_SCALAR(rates, '$.DJF') AS rate),
                    struct('SCR' AS code, JSON_EXTRACT_SCALAR(rates, '$.SCR') AS rate),
                    struct('DZD' AS code, JSON_EXTRACT_SCALAR(rates, '$.DZD') AS rate),
                    struct('GEL' AS code, JSON_EXTRACT_SCALAR(rates, '$.GEL') AS rate),
                    struct('BHD' AS code, JSON_EXTRACT_SCALAR(rates, '$.BHD') AS rate),
                    struct('EUR' AS code, JSON_EXTRACT_SCALAR(rates, '$.EUR') AS rate),
                    struct('BYR' AS code, JSON_EXTRACT_SCALAR(rates, '$.BYR') AS rate),
                    struct('XPD' AS code, JSON_EXTRACT_SCALAR(rates, '$.XPD') AS rate),
                    struct('SDG' AS code, JSON_EXTRACT_SCALAR(rates, '$.SDG') AS rate),
                    struct('PHP' AS code, JSON_EXTRACT_SCALAR(rates, '$.PHP') AS rate),
                    struct('AWG' AS code, JSON_EXTRACT_SCALAR(rates, '$.AWG') AS rate),
                    struct('NIO' AS code, JSON_EXTRACT_SCALAR(rates, '$.NIO') AS rate),
                    struct('SOS' AS code, JSON_EXTRACT_SCALAR(rates, '$.SOS') AS rate),
                    struct('BMD' AS code, JSON_EXTRACT_SCALAR(rates, '$.BMD') AS rate),
                    struct('LKR' AS code, JSON_EXTRACT_SCALAR(rates, '$.LKR') AS rate),
                    struct('CNY' AS code, JSON_EXTRACT_SCALAR(rates, '$.CNY') AS rate),
                    struct('CLF' AS code, JSON_EXTRACT_SCALAR(rates, '$.CLF') AS rate),
                    struct('STN' AS code, JSON_EXTRACT_SCALAR(rates, '$.STN') AS rate),
                    struct('CRC' AS code, JSON_EXTRACT_SCALAR(rates, '$.CRC') AS rate),
                    struct('CUC' AS code, JSON_EXTRACT_SCALAR(rates, '$.CUC') AS rate),
                    struct('MWK' AS code, JSON_EXTRACT_SCALAR(rates, '$.MWK') AS rate),
                    struct('MTL' AS code, JSON_EXTRACT_SCALAR(rates, '$.MTL') AS rate),
                    struct('XAF' AS code, JSON_EXTRACT_SCALAR(rates, '$.XAF') AS rate),
                    struct('XAG' AS code, JSON_EXTRACT_SCALAR(rates, '$.XAG') AS rate),
                    struct('IRR' AS code, JSON_EXTRACT_SCALAR(rates, '$.IRR') AS rate),
                    struct('SRD' AS code, JSON_EXTRACT_SCALAR(rates, '$.SRD') AS rate),
                    struct('XDR' AS code, JSON_EXTRACT_SCALAR(rates, '$.XDR') AS rate),
                    struct('KMF' AS code, JSON_EXTRACT_SCALAR(rates, '$.KMF') AS rate),
                    struct('WST' AS code, JSON_EXTRACT_SCALAR(rates, '$.WST') AS rate),
                    struct('ZAR' AS code, JSON_EXTRACT_SCALAR(rates, '$.ZAR') AS rate),
                    struct('NAD' AS code, JSON_EXTRACT_SCALAR(rates, '$.NAD') AS rate),
                    struct('KRW' AS code, JSON_EXTRACT_SCALAR(rates, '$.KRW') AS rate),
                    struct('NZD' AS code, JSON_EXTRACT_SCALAR(rates, '$.NZD') AS rate),
                    struct('TMT' AS code, JSON_EXTRACT_SCALAR(rates, '$.TMT') AS rate),
                    struct('MDL' AS code, JSON_EXTRACT_SCALAR(rates, '$.MDL') AS rate),
                    struct('ANG' AS code, JSON_EXTRACT_SCALAR(rates, '$.ANG') AS rate),
                    struct('BRL' AS code, JSON_EXTRACT_SCALAR(rates, '$.BRL') AS rate),
                    struct('MYR' AS code, JSON_EXTRACT_SCALAR(rates, '$.MYR') AS rate),
                    struct('LYD' AS code, JSON_EXTRACT_SCALAR(rates, '$.LYD') AS rate),
                    struct('AFN' AS code, JSON_EXTRACT_SCALAR(rates, '$.AFN') AS rate),
                    struct('YER' AS code, JSON_EXTRACT_SCALAR(rates, '$.YER') AS rate),
                    struct('GBP' AS code, JSON_EXTRACT_SCALAR(rates, '$.GBP') AS rate),
                    struct('DKK' AS code, JSON_EXTRACT_SCALAR(rates, '$.DKK') AS rate),
                    struct('AZN' AS code, JSON_EXTRACT_SCALAR(rates, '$.AZN') AS rate),
                    struct('PLN' AS code, JSON_EXTRACT_SCALAR(rates, '$.PLN') AS rate),
                    struct('ETB' AS code, JSON_EXTRACT_SCALAR(rates, '$.ETB') AS rate),
                    struct('AMD' AS code, JSON_EXTRACT_SCALAR(rates, '$.AMD') AS rate),
                    struct('VEF' AS code, JSON_EXTRACT_SCALAR(rates, '$.VEF') AS rate),
                    struct('NGN' AS code, JSON_EXTRACT_SCALAR(rates, '$.NGN') AS rate),
                    struct('KES' AS code, JSON_EXTRACT_SCALAR(rates, '$.KES') AS rate),
                    struct('IMP' AS code, JSON_EXTRACT_SCALAR(rates, '$.IMP') AS rate),
                    struct('UAH' AS code, JSON_EXTRACT_SCALAR(rates, '$.UAH') AS rate),
                    struct('TTD' AS code, JSON_EXTRACT_SCALAR(rates, '$.TTD') AS rate),
                    struct('XOF' AS code, JSON_EXTRACT_SCALAR(rates, '$.XOF') AS rate),
                    struct('PGK' AS code, JSON_EXTRACT_SCALAR(rates, '$.PGK') AS rate),
                    struct('BAM' AS code, JSON_EXTRACT_SCALAR(rates, '$.BAM') AS rate),
                    struct('ALL' AS code, JSON_EXTRACT_SCALAR(rates, '$.ALL') AS rate),
                    struct('CZK' AS code, JSON_EXTRACT_SCALAR(rates, '$.CZK') AS rate),
                    struct('NOK' AS code, JSON_EXTRACT_SCALAR(rates, '$.NOK') AS rate),
                    struct('BIF' AS code, JSON_EXTRACT_SCALAR(rates, '$.BIF') AS rate),
                    struct('CNH' AS code, JSON_EXTRACT_SCALAR(rates, '$.CNH') AS rate),
                    struct('TWD' AS code, JSON_EXTRACT_SCALAR(rates, '$.TWD') AS rate),
                    struct('IDR' AS code, JSON_EXTRACT_SCALAR(rates, '$.IDR') AS rate),
                    struct('GGP' AS code, JSON_EXTRACT_SCALAR(rates, '$.GGP') AS rate),
                    struct('USD' AS code, JSON_EXTRACT_SCALAR(rates, '$.USD') AS rate),
                    struct('BTN' AS code, JSON_EXTRACT_SCALAR(rates, '$.BTN') AS rate),
                    struct('COP' AS code, JSON_EXTRACT_SCALAR(rates, '$.COP') AS rate),
                    struct('OMR' AS code, JSON_EXTRACT_SCALAR(rates, '$.OMR') AS rate),
                    struct('DOP' AS code, JSON_EXTRACT_SCALAR(rates, '$.DOP') AS rate),
                    struct('CVE' AS code, JSON_EXTRACT_SCALAR(rates, '$.CVE') AS rate),
                    struct('BGN' AS code, JSON_EXTRACT_SCALAR(rates, '$.BGN') AS rate),
                    struct('UYU' AS code, JSON_EXTRACT_SCALAR(rates, '$.UYU') AS rate),
                    struct('TJS' AS code, JSON_EXTRACT_SCALAR(rates, '$.TJS') AS rate),
                    struct('ZWL' AS code, JSON_EXTRACT_SCALAR(rates, '$.ZWL') AS rate),
                    struct('MZN' AS code, JSON_EXTRACT_SCALAR(rates, '$.MZN') AS rate),
                    struct('RSD' AS code, JSON_EXTRACT_SCALAR(rates, '$.RSD') AS rate),
                    struct('UGX' AS code, JSON_EXTRACT_SCALAR(rates, '$.UGX') AS rate),
                    struct('UZS' AS code, JSON_EXTRACT_SCALAR(rates, '$.UZS') AS rate),
                    struct('MGA' AS code, JSON_EXTRACT_SCALAR(rates, '$.MGA') AS rate),
                    struct('AED' AS code, JSON_EXTRACT_SCALAR(rates, '$.AED') AS rate),
                    struct('KYD' AS code, JSON_EXTRACT_SCALAR(rates, '$.KYD') AS rate),
                    struct('ZMW' AS code, JSON_EXTRACT_SCALAR(rates, '$.ZMW') AS rate),
                    struct('GTQ' AS code, JSON_EXTRACT_SCALAR(rates, '$.GTQ') AS rate),
                    struct('BBD' AS code, JSON_EXTRACT_SCALAR(rates, '$.BBD') AS rate),
                    struct('ERN' AS code, JSON_EXTRACT_SCALAR(rates, '$.ERN') AS rate),
                    struct('KGS' AS code, JSON_EXTRACT_SCALAR(rates, '$.KGS') AS rate),
                    struct('VUV' AS code, JSON_EXTRACT_SCALAR(rates, '$.VUV') AS rate),
                    struct('ARS' AS code, JSON_EXTRACT_SCALAR(rates, '$.ARS') AS rate),
                    struct('LAK' AS code, JSON_EXTRACT_SCALAR(rates, '$.LAK') AS rate),
                    struct('KWD' AS code, JSON_EXTRACT_SCALAR(rates, '$.KWD') AS rate),
                    struct('XCD' AS code, JSON_EXTRACT_SCALAR(rates, '$.XCD') AS rate),
                    struct('BND' AS code, JSON_EXTRACT_SCALAR(rates, '$.BND') AS rate),
                    struct('GYD' AS code, JSON_EXTRACT_SCALAR(rates, '$.GYD') AS rate)
                    ] AS currency
         FROM FIRST_RESULT
     ),
     CURRENCY_FLAT AS (
         SELECT day, code, rate
         FROM CURRENCY_ARRAY, UNNEST(CURRENCY_ARRAY.currency) AS t2
         WHERE CURRENCY_ARRAY.day IS NOT NULL
     )
SELECT t1.day, t1.code, CAST(t1.rate AS FLOAT64) AS usd_rate,
       SAFE_DIVIDE(1,CAST(t1.rate AS FLOAT64))*CAST(t2.rate AS FLOAT64) AS krw_rate
FROM CURRENCY_FLAT AS t1
         JOIN CURRENCY_FLAT AS t2 ON t2.day = t1.day AND t2.code = 'KRW'
ORDER BY 1,2