{{
    config(
        materialized='table',
        schema='edw_mart',
        alias='MART_PARTNER_AGG_D'
    )
}}

{% set partner_metric_models = [
    'INT_PARTNER_AGG_SALES',
    'INT_PARTNER_AGG_ONSALE',
    'INT_PARTNER_AGG_MAIN_ACTIVITY',
    'INT_PARTNER_AGG_REVIEW',
    'INT_PARTNER_AGG_CONFIRM_RATE'
] %}

WITH PARTNER_METRICS_UNION AS (
{% for m in partner_metric_models %}
SELECT
    T.*
FROM {{ ref(m) }} T
{% if not loop.last %}UNION ALL{% endif %}
{% endfor %}
)
SELECT
    M.PARTNER_ID
  , IFNULL(MAX(M.RESVE_CNT), 0) AS RESVE_CNT
  , IFNULL(MAX(M.SALES_KRW_PRICE), 0) AS SALES_KRW_PRICE
  , IFNULL(MAX(M.USER_CNT), 0) AS USER_CNT
  , IFNULL(MAX(M.CURRENT_RESVE_CNT), 0) AS CURRENT_RESVE_CNT
  , IFNULL(MAX(M.ONSALE_CNT), 0) AS ONSALE_CNT
  , MAX(M.MAIN_ACTIVITY_CITY_CD) AS MAIN_ACTIVITY_CITY_CD
  , MAX(M.MAIN_ACTIVITY_COUNTRY_NM) AS MAIN_ACTIVITY_COUNTRY_NM
  , MAX(M.MAIN_ACTIVITY_MRT_TYPE) AS MAIN_ACTIVITY_MRT_TYPE
  , IFNULL(MAX(M.REVIEW_CNT), 0) AS REVIEW_CNT
  , MAX(M.REVIEW_SCORE_AVG) AS REVIEW_SCORE_AVG
  , MAX(M.CONFIRM_RATE) AS CONFIRM_RATE
  , DATETIME_ADD(CURRENT_TIMESTAMP(), INTERVAL 9 HOUR) AS DW_LOAD_DT
FROM PARTNER_METRICS_UNION M
WHERE M.PARTNER_ID IS NOT NULL
GROUP BY M.PARTNER_ID
