
WITH failures AS (
  SELECT RESVE_ID
       , CREATE_KST_DATE
  FROM {{ ref('MART_SALE_D') }}
  WHERE CREATE_KST_DATE >= '2022-01-01'
  GROUP BY RESVE_ID, CREATE_KST_DATE
  HAVING MAX(CASE WHEN KIND = 1 THEN 1 ELSE 0 END) = 0
     AND MAX(CASE WHEN KIND = 2 THEN 1 ELSE 0 END) = 1
)

SELECT COUNT(*) AS failure_count
FROM failures
HAVING failure_count > 50